### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by BroadSkate** [CzechPMDevs/MultiWorld#1]
Can you add a way for per world gamemodes?

**Comment by GamakCZ** [comment]
Currently I have a problem with correcting mistakes, but in the future I could ;-)

**Comment by GamakCZ** [comment]
I'm working on a plugin CreativeWorld to be done, I'll give you a link to it.

**Comment by GamakCZ** [comment]
CreativeWorld je ve vývoji, ale jeho funkce jsou nyní také v WorldManager.

**Comment by GamakCZ** [comment]
Added (https://github.com/CzechPMDevs/MultiWorld/commit/874d89bb94371ee2334713f873a1c4d5498d0f16)
