### ISSUE TITLE
IT CRASHES!!

### ISSUE THREAD

**Issue by FlakyHeart** [CzechPMDevs/MultiWorld#104]
- Issue Description: I created worlds with /mw command... Okay... No errors... And then when i try to load the world i’ve created and it just crashes MY ENTIRE SERVER!!!

- Version: 1.5.2

- Server Version: Pocketmine 3.11.8 ( 1.14.60 PE)

- Crashdump, backtrace or other files: There is not. It just crashes and that’s it. No log’s.

**Comment by Endermanbugzjfc** [comment]
there will be at least 1 crash message or some debug messages if it crashes as a runtime exception or something

**Comment by Endermanbugzjfc** [comment]
And i think the world is already loaded after u create it or even it will load automatically if u teleports into it

**Comment by MonoAdrian23** [comment]
No Crashdump?
Look into console.
