### ISSUE TITLE
How to get structure ?

### ISSUE THREAD

**Issue by benda95280** [CzechPMDevs/MultiWorld#113]
Hello,

How we could test the structure generator ?

Thanks :)

**Comment by benda95280** [comment]
Hum ...
From what i've read, it seems only Villager structure has been added ?
Why not use based Json file for the settings ? (like 'feature_rule')

**Comment by MonoAdrian23** [comment]
Only Pillager Outpost is loaded.
All other structures crashs the Async worker.
