### ISSUE TITLE
Items are transfered acrossed worlds

### ISSUE THREAD

**Issue by BeastBomber23** [CzechPMDevs/MultiWorld#115]
- Issue Description: Switching worlds keeps the players items in inventory any plugins to fix that also the player respawns in the hub

- Version: Devbuild 153

- Server Version: Pocketmine 3.15.1 Bedrock Edition v1.16.20 protocol version 408

- Crashdump, backtrace or other files:
None

**Comment by HydroGames-dev** [comment]
Try using PerWorldInventory 
for the items

**Comment by BeastBomber23** [comment]
thanks bro
