### ISSUE TITLE
'Server Lobby' won't change

### ISSUE THREAD

**Issue by enzipenzo** [CzechPMDevs/MultiWorld#116]
- Issue Description: I can't change the 'server lobby'. I tried doing it in /mw manage, and then when I use another problem that puts me in the server lobby every time I log in, called AlwaysSpawn, I just go back to the default world spawn.

- Version: 1.5.2

- Server Version: 3.15.1

- Crashdump, backtrace or other files:

**Comment by supercrafter333** [comment]
This is not a bug by MultiWorld, please close your Issue.
