### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by ghost** [CzechPMDevs/MultiWorld#132]
I hope you update the MultiWorld plugin to a good and stable plugin on PM3 to the poggit release

**Comment by MonoAdrian23** [comment]
I don't think so.
Use another Software for better gameplay

**Comment by TheBalkanDev** [comment]
@MonoAdrian23 Which? For example?

**Comment by DragonWizard975** [comment]
hope this helps :) https://github.com/CzechPMDevs/MultiWorld/issues/146#issuecomment-857490939
