### ISSUE TITLE
SugarCane generation

### ISSUE THREAD

**Issue by Steellgold** [CzechPMDevs/MultiWorld#133]
- Issue Description: Adding block generation

It's possible to add new genration, for example, the Sugar Can ?

- Version: Last (1.5.2)

- Server Version: Last PocketMine-Version

**Comment by MonoAdrian23** [comment]
No, this plugin is down!!!!!!!!

Gaëtan H <notifications@github.com> schrieb am Sa., 6. März 2021, 12:57:

**Comment by Steellgold** [comment]
I use api of this plugin to generate a normal custom world for my "server" so.. you don't have another plugin to propose then ? if this one is abandonned
