### ISSUE TITLE
Error syntax

### ISSUE THREAD

**Issue by Steellgold** [CzechPMDevs/MultiWorld#134]
- Issue Description: I have this error on generate or walk in Normal World Generated

- Version: Last

- Server Version: Last

`[17:20:17] [Asynchronous Worker #0 thread/CRITICAL]: ErrorException: "Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)`" (EXCEPTION) in "plugins/World/src/czechpmdevs/multiworld/generator/normal/object/BigOakTree" at line 141
`

**Comment by MonoAdrian23** [comment]
You can create thousand issues!
This Plugin is out of support!

Gaëtan H <notifications@github.com> schrieb am So., 7. März 2021, 17:22:

**Comment by MonoAdrian23** [comment]
You can create thousand issues!
This plugin is out of support!
