### ISSUE TITLE
Update!!

### ISSUE THREAD

**Issue by MrNinja008** [CzechPMDevs/MultiWorld#154]
- Issue Description: pls fix The Custom Generator error pls! It will be helpful if you fix it for latest pm3 verison

- Version: 1.5.3

- Server Version: 3.20.0

- Crashdump, backtrace or other files:

**Comment by MonoAdrian23** [comment]
Without Errors!!!!!! 
No fix!

**Comment by MrNinja008** [comment]
> Without Errors!!!!!!
> No fix!

Vik know what i am talking about lol you can only use custom generator in php7.5 i need it to be latest version since he only said that in my dm i made this issue so he dont forgot this

**Comment by MrNinja008** [comment]
@VixikHD

**Comment by MrNinja008** [comment]
You Fixed Custom World For latest pmmp verison? I already reported the error on your dms
