### ISSUE TITLE
Mesa/Jungle/Caves (Only a Question) 

### ISSUE THREAD

**Issue by MonoAdrian23** [CzechPMDevs/MultiWorld#155]
- Issue Description: Is it planned to add more Biomes? 
- And fix the Custom Generator Issues? 
- Using Fly or /wild doenst load chunks. 
- There are many Issues for it. 

- Version:

- Server Version:

- Crashdump, backtrace or other files:

**Comment by MonoAdrian23** [comment]
And please, dont say use the Release. 
This answer fix nothing

**Comment by VixikHD** [comment]
Seems like support request. Head to our discord if you are looking for a help
