### ISSUE TITLE
[Feature] Add support for PocketMine-MP 4.

### ISSUE THREAD

**Issue by DidntPot** [CzechPMDevs/MultiWorld#160]

**Comment by MonoAdrian23** [comment]
Pocketmine 4? 
Ten Years later?

**Comment by DidntPot** [comment]
PM4 is supposed to release with update.

**Comment by MonoAdrian23** [comment]
Wich one? 
Minecraft 1.20.0? 
Xddddd

**Comment by MonoAdrian23** [comment]
See you in 3 Years 
Pocketmine xd

**Comment by VixikHD** [comment]
1.6 doesn't even support pocketmine 3.0. 4.0 will be supported after releasing 1.6 for 3.0
