### ISSUE TITLE
Forms classes Missing

### ISSUE THREAD

**Issue by DumbChester** [CzechPMDevs/MultiWorld#163]
Check ManageSubCommand, Using a non existent SimpleForms, CustomForms and FormResponse

**Comment by VixikHD** [comment]
learn how composer and libraries works

**Comment by DumbChester** [comment]
Sorry, Idk much about PHP but it throws this error everytime, So i manually downloaded the library needed from the repo, 

this is what i meant by missing forms classes BTW:(how do i fix? except for manually putting the path? ) 

2021-07-05 [16:24:10] [Server thread/INFO]: Enabling MultiWorld v1.6.0-beta1

2021-07-05 [16:24:10] [Server thread/CRITICAL]: Error: "Class 'czechpmdevs\multiworld\util\FormManager' not found" (EXCEPTION) in "plugins/mwVix.phar/src/czechpmdevs/multiworld/MultiWorld" at line 87

2021-07-05 [16:24:10] [Server thread/CRITICAL]: #0 pmsrc/src/pocketmine/plugin/PluginBase(116): czechpmdevs\multiworld\MultiWorld->onEnable()

2021-07-05 [16:24:10] [Server thread/CRITICAL]: #1 pmsrc/src/pocketmine/plugin/PluginManager(552): pocketmine\plugin\PluginBase->setEnabled(boolean 1)

**Comment by MonoAdrian23** [comment]
Use Powernukkit and youre Problems are done xd

**Comment by DumbChester** [comment]
> Use Powernukkit and youre Problems are done xd

I mean i can fix by manually putting the file in the required path (Not composer ofc) , No prob, But i think im missing something, or something is broken, I wanna know, Sure that other Newbs like me out there would get same Error or smth.

**Comment by VixikHD** [comment]
> Use Powernukkit and youre Problems are done xd

Power nukkit has more bugs than the most buggy version of multiworld

**Comment by VixikHD** [comment]
> > Use Powernukkit and youre Problems are done xd
> 
> I mean i can fix by manually putting the file in the required path (Not composer ofc) , No prob, But i think im missing something, or something is broken, I wanna know, Sure that other Newbs like me out there would get same Error or smth.

I'd recommend to use either released version, or latest dev https://poggit.pmmp.io/ci/CzechPMDevs/MultiWorld/MultiWorld/dev:186

**Comment by MonoAdrian23** [comment]
Powernukkit is much more stable as pocketmine 
Pocketmine lives in 1.11 from Worlds and blocks. 
Multiworlds Custom Gen is blame and cant load a anvil standart world without bugs. 
Yeahhhh more Bugs than Powernukkit xd. 
You cant develope a simple Generator and call this better xd.

**Comment by VixikHD** [comment]
There is 'development' branch known as '4.0' which support new blocks too. PocketMine has not good generator as it wasn't made for that purpose. It's server software which aims to performance, stability and friendly api. That means if you want some feature, you can simply implement it with plugins. Also although PocketMine is written in such a slow language (php), it's performance is better than nukkit.
