### ISSUE TITLE
Gamerule Bug

### ISSUE THREAD

**Issue by DumbChester** [CzechPMDevs/MultiWorld#167]
MCPE Version:1.17 
PMMP Version: 3.21
PHP Version: 7.4
Plugin Version: Latest dev release (Poggit)
is this just me or?

Changing Gamerules trough /mw manage Form
![Screenshot_2021-07-06-02-43-30-51_5c8300b655012b1930f2e0a7b81bf6a9.jpg](https://user-images.githubusercontent.com/30301114/124509360-63c4a800-de04-11eb-96b0-4291d854dea6.jpg)

**Comment by VixikHD** [comment]
Thy for report!
