### ISSUE TITLE
Mesa Bug

### ISSUE THREAD

**Issue by TheBalkanDev** [CzechPMDevs/MultiWorld#173]
1. 90% of the Caves in the Mesa Biome, looked like someone came and exploded some tnt, there are just big holes underground.
I will try fixing it for myself.

2. Mesa Generates to often.

3. Can you maybe add Structures in the Custom Gen.
Ive tried to implement it but yeah, its just sucks.

**Comment by TheBalkanDev** [comment]
You can use the Structures from BetterGen

**Comment by VixikHD** [comment]
Invalid usage of issue template
