### ISSUE TITLE
Be able to switch worlds for players

### ISSUE THREAD

**Issue by Skyde72** [CzechPMDevs/MultiWorld#174]
**Is your feature request related to a problem? Please describe.**
I want to make it so I could switch player's worlds

**Describe the solution you'd like**
I'd like a command such as /mw transfer <player> <world> and an API

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by VixikHD** [comment]
Are you looking for `/mw teleport <worldName> [player]` command?

**Comment by Skyde72** [comment]
thanks but how to incorporate the API with my plugins

**Comment by Skyde72** [comment]
(teleport api)

**Comment by VixikHD** [comment]
Player->teleport(new Position(int $x, int $y, int $z, Level $world))
