### ISSUE TITLE
Custom genration!

### ISSUE THREAD

**Issue by MrNinja008** [CzechPMDevs/MultiWorld#175]
**Describe the bug**
Custom genration is messed up misa biome and red desert and dark oak biome spawn in same place like merged everywhere it looks weird
**To Reproduce**
1. Go to 'mw manage'
2. Click on 'create world'
3. Scroll down to 'custom genration'

**Expected behavior**
It will be good if biomes looks normal not messed up...
**Screenshots**
If applicable, add screenshots to help explain your proble
m.

**Desktop (please complete the following information):**
- php version [e.g. 7.4.11, 8.0]
- BuilderTools Version [e.g. dev#142, Release 1.5.3]

**Additional context**

**Comment by VixikHD** [comment]
Invalid usage of issue template (specify OS and Versions)
