### ISSUE TITLE
No default world - Crash

### ISSUE THREAD

**Issue by EndermanLetsPlay** [CzechPMDevs/MultiWorld#181]
**Describe the bug**
The server stops and does not start up with the reason "2021-07-16 [17:58:26] [Server thread/ERROR]: Could not load world "Spawn": Unknown generator "void"
2021-07-16 [17:58:26] [Server thread/EMERGENCY]: No default world has been loaded"

**To Reproduce**
1. Install version Dev #199, #200 or #201 instead of #198
2. Restart server
3. Server stops

**Expected behavior**
The server should start. It does so up to version Dev #198.

**Desktop (please complete the following information):**
- php version [7.4]
- BuilderTools Version [Dev#148]

**Additional context**

**Comment by Wertzui123** [comment]
Yes, I can confirm this.

**Comment by Wertzui123** [comment]
This was caused by moving the generator registration from `onLoad` to `onEnable` in bdcdc86b5d2ab209a0eb73353886beb5eed7d394.

**Comment by xKurt** [comment]
Still says
```[14:52:20] [Server thread/ERROR]: Could not load world "hub": Unknown generator "void"
[14:52:20] [Server thread/EMERGENCY]: No default world has been loaded```
