### ISSUE TITLE
Plugin doesn't load

### ISSUE THREAD

**Issue by xKurt** [CzechPMDevs/MultiWorld#182]
Using the latest build and still says:
`[14:52:20] [Server thread/ERROR]: Could not load world "hub": Unknown generator "void"`
`[14:52:20] [Server thread/EMERGENCY]: No default world has been loaded`

**Comment by VixikHD** [comment]
Are you sure?

**Comment by xKurt** [comment]
yep

**Comment by VixikHD** [comment]
Make sure you use [latest dev version](https://poggit.pmmp.io/r/132413/MultiWorld_dev-202.phar), I tested it several times and it worked.
