### ISSUE TITLE
Default world doesnt changes

### ISSUE THREAD

**Issue by ghost** [CzechPMDevs/MultiWorld#183]
**Describe the bug**
I can change the default world, when i restart my server, the default world still the same.

**To Reproduce**
1. do /mw update default (world) in a non default world
2. Try to delete the last default world, it allows you to delete it because is no more the default world.
3. Restart the server.
4. See how you respawned in a different world you didnt put as default (usually called "world")
5. Try to delete that world
6. Receive the message "You cannot delete  default world!"

**Expected behavior**
Being able to change the default world normally.

**Desktop (please complete the following information):**
- OS: [My host uses Linux]
- php version [sorry idk]
- BuilderTools Version [version 1.2.0-beta4]

**Additional context**
A world called "world" is created everytime i restart my server, even if i deleted it.

**Comment by Gezou** [comment]
Hope this will be fixed soon it's really annoying 
And when I change the default world in server proprietors it's doesn't start my server so yea

**Comment by VixikHD** [comment]
Fixed in https://github.com/CzechPMDevs/MultiWorld/commit/e4baed4248a1d0ef4e5a55f0282e948bec75daa8
