### ISSUE TITLE
Hi there I tryna upload a maps and when I load the map it says "could not load mao for map" plss help

### ISSUE THREAD

**Issue by SlidPurse** [CzechPMDevs/MultiWorld#184]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- php version [e.g. 7.4.11, 8.0]
- BuilderTools Version [e.g. dev#142, Release 1.5.3]

**Additional context**

**Comment by MonoAdrian23** [comment]
Send the Error complete. 
I hope you know, only Minecraft Java 1.12 Maps are supported.

**Comment by VixikHD** [comment]
Invalid issue template.

**Comment by SlidPurse** [comment]
I did and it says "Cannot Identify Format of world"

**Comment by MonoAdrian23** [comment]
Yes 
The world haves a incorrect format. 
Only worlds in format pmanvil or anvil work.

**Comment by SlidPurse** [comment]
Hi there I have new problem when I start the server it says "crashdumps"
pls help
