### ISSUE TITLE
Plugin Not Loaded

### ISSUE THREAD

**Issue by ItzFel** [CzechPMDevs/MultiWorld#185]
[Server thread/CRITICAL]: Error: "Class 'pocketmine\world\generator\GeneratorManager' not found" (EXCEPTION) in "plugins/MultiWorld (2).phar/src/czechpmdevs/multiworld/MultiWorld" at line 68
[Server thread/CRITICAL]: #0 pmsrc/src/pocketmine/plugin/PluginManager(182): czechpmdevs\multiworld\MultiWorld->onLoad()
[Server thread/CRITICAL]: #1 pmsrc/src/pocketmine/plugin/PluginManager(346): pocketmine\plugin\PluginManager->loadPlugin(string[42] /root/sbupdate/plugins/MultiWorld (2).phar, array[2])
[Server thread/CRITICAL]: #2 pmsrc/src/pocketmine/Server(1529): pocketmine\plugin\PluginManager->loadPlugins(string[23] /root/sbupdate/plugins/)
[Server thread/CRITICAL]: #3 pmsrc/src/pocketmine/PocketMine(291): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[15] /root/sbupdate/, string[23] /root/server/plugins/)
[Server thread/CRITICAL]: #4 pmsrc/src/pocketmine/PocketMine(321): pocketmine\server()
[Server thread/CRITICAL]: #5 pmsrc(11): require(string[70] phar:///root/server/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by VixikHD** [comment]
It is already fixed in latest dev version.
