### ISSUE TITLE
Bug in EventListener

### ISSUE THREAD

**Issue by morcheysha77** [CzechPMDevs/MultiWorld#190]
**Describe the bug**
When a player dies and once it bites the world is deleted, as in a duel plugin which deletes the world, once the match is over, the GetLevelNonNull method returns an internal server error given that the level is fine is well null to solve this bug it would be necessary to put an option with a condition or to use getLevel, thank you for reading, Regards Morcheysha77.

**To Reproduce**
1. Go to 'remove the world on PlayerDeathEvent or other Event, if it require getLevelNonNull'
4. See the error 

**Screenshots**
'Position world is null'

**Desktop (please complete the following information):**
- OS: [Every OS]
- php version [Every PHP version]

**Comment by VixikHD** [comment]
Please, upload either crashdump or stack trace from internal server error.
