### ISSUE TITLE
No queda gualdado la configuración de gamerule 

### ISSUE THREAD

**Issue by mclovinIG** [CzechPMDevs/MultiWorld#192]
Al usar gamerule y modificar el mundo no se queda gualdado la configuración 

Por ejemplo al cambia gamerule PVP false a PVP true , ocurre que se cambia pero cuando ni servidor se reinicia se borra la configuración

**Comment by VixikHD** [comment]
I am sorry, but unless you use don't the issue template format the correct way, I cannot help you. Also, use English
