### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mclovinIG** [CzechPMDevs/MultiWorld#195]
Tengo un fallo con el plugin multiword causando por los mapa de mi servidor , le comentó anterior mente usaban el plugin sin ningún error luego de pasa las semanas me daba error del server close la cual el error es por los mapa que tengo en mi servidor lo que pasa es que tengo que borra los mapa para que le plugin funcione correctamente quería saber si hay solución a ese problema sin necesidad de borra mapa

**Comment by VixikHD** [comment]
Use English please
