### ISSUE TITLE
PLUGIN DOESN’T LOAD

### ISSUE THREAD

**Issue by MadooxMc** [CzechPMDevs/MultiWorld#197]
your plugin doesn't load on my server ? what can i do? put screen shot of why ? my empty plugin_data lol i tried with 0 plugin to see if the bug is caused by another plugin but same issue. DON’T CLOSE MY ISSUE.

**Comment by VixikHD** [comment]
This issue tracker is ONLY for problems, whose are certainly related to some mistake in source code. As you are not even able to respect issue submission rules (Correct issue format), I cannot do anything with that. If you would like to help, you can either contact me on discord, if you want some kind of support, or follow the issue format (for bug report or for feature request).
