### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Iglesias12** [CzechPMDevs/MultiWorld#199]
well I have a problem with the Multiword plugin, the problem is:

When I teleport to a map, the game takes me out you will say that the map is damaged but it is not.

The plugin previously allowed me to go to that map, but an error occurred and now it pulls me out when I go to it.

**Comment by Iglesias12** [comment]
well I have a problem with the Multiword plugin, the problem is:

When I teleport to a map, the game takes me out you will say that the map is damaged but it is not.

The plugin above allowed me to go to that map, but an error occurred and now it pulls me out when I go to it

**Comment by VixikHD** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.
