### ISSUE TITLE
Feature request: add world editor

### ISSUE THREAD

**Issue by jasonwynn10** [CzechPMDevs/MultiWorld#2]
World edit is also in the advanced category of world management, so why not add it to this plugin?

**Comment by GamakCZ** [comment]
If you want to make in my WorldManager included a World Edit, add it yourself by using the pull request.

**Comment by GamakCZ** [comment]
I created a new BuilderTools plugin that has these commands. If you need them, download plugin [here](https://github.com/CzechPMDevs/BuilderTools/releases/tag/1.0.0).
