### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GabriMode** [CzechPMDevs/MultiWorld#200]
**Describe the bug**
Possibly the plugin has an error, when teleporting to another world, the food and life bar are automatically filled.

**Comment by VixikHD** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.
