### ISSUE TITLE
Could not load world because of unexisting generator

### ISSUE THREAD

**Issue by MrNinja008** [CzechPMDevs/MultiWorld#201]
**Describe the bug**
Void world, custom gen world not loading

**To Reproduce**
Genarate Void World or custom world 
Restart the server
Enjoy could not able to load world error
**Expected behavior**
Mw needs to load custom gen and void world since i am using it from multiworld Genarator
**Screenshots**

**Desktop (please complete the following information):**
- OS: [LINUX]
- php version [ 7.4.]
- Multiworld 1.6.0-Beta3

**Additional context**
2021-08-27 [16:42:36] [Server thread/ERROR]: Could not load world "SMP2": Unknown generator "normal_mw"
2021-08-27 [16:42:36] [Server thread/ERROR]: Could not load world "Warzone": Unknown generator "void"

**Comment by VixikHD** [comment]
What way are you loading those worlds?

**Comment by MrNinja008** [comment]
No I checked the version by doing about multiworld IT SAYS 1.6.0beta-3
Also it is not loading on startup but you can load manually by cmd

**Comment by MrNinja008** [comment]
> What way are you loading those worlds?

Wait what how unexisting generator? I created void and custom Genaration world with your plugin gen and it cant load on startup

**Comment by MrNinja008** [comment]
You need to do /mw load void

**Comment by MrNinja008** [comment]
To load

**Comment by VixikHD** [comment]
PocketMine usually doesn't load worlds on startup without any modifications such as modified `pocketmine.yml` or plugins. What way do you use to load the worlds?

**Comment by MrNinja008** [comment]
I dont use any plugins to load worlds

**Comment by VixikHD** [comment]
Then I don't understand how the error could occur

**Comment by VixikHD** [comment]
Could you please record a video with reproducing it?

**Comment by MrNinja008** [comment]
> Could you please record a video with reproducing it?

K
