### ISSUE TITLE
Gamerule

### ISSUE THREAD

**Issue by FiePaw** [CzechPMDevs/MultiWorld#203]
[Server thread/CRITICAL]: TypeError: "Argument 1 passed to czechpmdevs\multiworld\level\gamerules\GameRules::czechpmdevs\multiworld\level\gamerules\{closure}() must be an instance of pocketmine\nbt\tag\StringTag, instance of pocketmine\nbt\tag\ByteTag given" (EXCEPTION) in "plugins/MultiWorld.phar/src/czechpmdevs/multiworld/level/gamerules/GameRules" at line 193

**Comment by MonoAdrian23** [comment]
Please use the Issue Template correct!
Without youre using Version, noone can help you

**Comment by VixikHD** [comment]
Without knowing your Plugin version, PocketMine-MP version, OS, PHP, Client version, or other plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.
