### ISSUE TITLE
Gamerule reset

### ISSUE THREAD

**Issue by HyoukaKu** [CzechPMDevs/MultiWorld#204]
**Describe the bug**
Basically whenever i change the gamerule of the world ''Naturalregeneration'' to true and it works after server close and reopens (restart) it turns it back to false even tho it says true in gmerules file in multiworld folder

im using multiworld 1.6.0-beta3
and PocketMine-MP 3.22.4
the issue was also in PocketMine-MP 3.22.2
**To Reproduce**
get latest pocketmine mp 3.22.4 phar
and latest multiworld phar
set the gamerule to something different than the default (Naturalregeneration)
stop the server after the gamerule was successfully changed
start the server

**Expected behavior**
you will see that naturalregeneration was reseted to the default and not to what u put it to before restartin the server
(its disabled in my world and whenever i turn it true it resets back to false after server restart)

**Desktop (please complete the following information):**
- OS: Windows 10 tho im using a host called Minehub their site "minehub.de" im using the pro plan 8gs ram
- php version [7.4.11] 
- BuilderTools Version 1.2.0-beta4

**Additional context**
i tried disabling naturalregeneration in another world and it got reseted to true after server restart

**Comment by VixikHD** [comment]
Fixed in featue/pm4.0 branch
