### ISSUE TITLE
The flat world will not load.

### ISSUE THREAD

**Issue by zerogamikun** [CzechPMDevs/MultiWorld#206]
When I try to load a flat world, it freezes in midair and I can't do anything.

Please fix this if you can.

**Comment by VixikHD** [comment]
Without knowing your Plugin version, PocketMine-MP version, OS, PHP, Client version, or other plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.
