### ISSUE TITLE
Jungle biome does not have any populators

### ISSUE THREAD

**Issue by YaNIND** [CzechPMDevs/MultiWorld#219]
**Describe the bug**
I using multiworld 1.6.0-beta4 the bug is jungle not have biome but the grass create the biome (grass colors like green colorfull) but don't have jungle tree

**To Reproduce**
1. Using multiworld-1.6.0-beta4
2. Create World
3. See Biome

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- php version [e.g. 7.4.11, 8.0]
- BuilderTools Version [e.g. dev#142, Release 1.5.3]

**Additional context**

**Comment by VixikHD** [comment]
resolved in 2.0
