### ISSUE TITLE
Hey when the new update will be come for PocketMine 3.23.1

### ISSUE THREAD

**Issue by sani992** [CzechPMDevs/MultiWorld#220]
**I needed the new update because the minecraft and pocketmine both are updated pls I request to update**

**Comment by MonoAdrian23** [comment]
Check the Dev Builds

**Comment by sani992** [comment]
Where?

**Comment by MonoAdrian23** [comment]
https://poggit.pmmp.io/ci/CzechPMDevs/MultiWorld/MultiWorld
