### ISSUE TITLE
please update pmmp 3.26.1 or mcpe 1.18

### ISSUE THREAD

**Issue by azhimmanru** [CzechPMDevs/MultiWorld#234]
**Is this request related to any other issues? Please list them here.**
none

**Update information:**
New protocol version: 450
New Minecraft version: 1.17.2
PocketMine commit which changed the protocol: 57d274901d4a0ca65881f7199af85ee2e5d0820f

please update pmmp 3.26.1 or mcpe 1.18, i really need this
not working in version pmmp 3.26.1 or mcpe 1.18

**Comment by VixikHD** [comment]
Protocol version 450 is already added

**Comment by azhimmanru** [comment]
okay thanks

Pada tanggal Rab, 1 Des 2021 pukul 15.35 VixikHD ***@***.***>
menulis:
