### ISSUE TITLE
No compatible 3.26

### ISSUE THREAD

**Issue by SPMP2** [CzechPMDevs/MultiWorld#235]
Touch block on end/nether and 4 block removed

**Comment by SPMP2** [comment]
Please try

**Comment by VixikHD** [comment]
Without knowing your Plugin version, PocketMine-MP version, OS, PHP, Client version, other plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

**Comment by SPMP2** [comment]
Are you disabled man? No need to give you anything !!! Ok to make you happy. 
API 3.26.1 
PLUGINS: 1 : MULTIWORLD 
TO REPRODUCE THIS BUG GO ON NETHER / END AND TOUCH A BLOCK , BLOCKS ARE REMOVED (5 BLOCK REMOVED)  (LIKE A BRUSH OF BLOCKSNIPER)
