### ISSUE TITLE
BUG Touch/Breack block End/Nether

### ISSUE THREAD

**Issue by SPMP2** [CzechPMDevs/MultiWorld#236]
Are you disabled man? No need to give you anything !!! Ok to make you happy. 
API 3.26.1 
PLUGINS: 1 : MULTIWORLD 
TO REPRODUCE THIS BUG GO ON NETHER / END AND TOUCH/BREACK A BLOCK , BLOCKS ARE REMOVED (5 BLOCK REMOVED)  (LIKE A BRUSH OF BLOCKSNIPER) 

__Originally posted by @SPMP2 in https://github.com/CzechPMDevs/MultiWorld/issues/235#issuecomment-985143527__

**Comment by VixikHD** [comment]
I am providing this software completely for free. If you aren't able to follow the pre-formatted pattern, as I said, I am not able to fix the issue due to missing information. Being vulgar or using caps lock also doesn't really help..

**Comment by SPMP2** [comment]
Ok i understand, I apologize.. but i think if you test, the bug will occur because i have teating on 3.26.1 in php 8 without any plugin just Multiworld and the bug occur

**Comment by VixikHD** [comment]
So.. could you please provide missing information (used plugin version and server os)

**Comment by SPMP2** [comment]
I'm using windows 10 (idk if server os is that)
And version of plugin: Worldguars_Dev232

**Comment by VixikHD** [comment]
#237
