### ISSUE TITLE
Blocks are moved 4 subchunks up in Nether and End dimensions

### ISSUE THREAD

**Issue by VixikHD** [CzechPMDevs/MultiWorld#237]
- Issue Description: All the blocks in Nether / End dimensions are moved 4 subchunks up. Interacting with those blocks makes the server show the real block at touched position.

- Version: 1.6.0-beta6

- Server Version: PocketMine-MP 3.26.1

- Crashdump, backtrace or other files: https://streamable.com/729ne9

**Comment by VixikHD** [comment]
Due to missing api in server software there is not possibility to fix this problem right now. **However, it's possible to debug this problem disabling [dimension handling in config.yml](https://github.com/CzechPMDevs/MultiWorld/blob/main/resources/config.yml#L21).**

**Comment by usser1976** [comment]
> Aufgrund fehlender API in der Serversoftware gibt es derzeit keine Möglichkeit, dieses Problem zu beheben. **Es ist jedoch möglich, dieses Problem zu beheben, indem die deaktiviert [Dimensionsbehandlung in config.yml wird ](https://github.com/CzechPMDevs/MultiWorld/blob/main/resources/config.yml#L21). **

unfortunately this does not work for us :(

**Comment by VixikHD** [comment]
Set it in the config this way: `handle-dimensions: false`

**Comment by usser1976** [comment]
> Set it in the config this way: `handle-dimensions: false`

i have

**Comment by DRAGKILLS** [comment]
I think u can fix it with blockplace event and block break event but idk if its right or no

**Comment by VixikHD** [comment]
> I think u can fix it with blockplace event and block break event but idk if its right or no

It's not that easy

**Comment by Willtom999** [comment]
Is nether is buged because no move World nether

**Comment by Willtom999** [comment]
https://user-images.githubusercontent.com/83521998/146101581-a055db50-affc-4984-bfb3-3e7849bb671c.MP4

**Comment by VixikHD** [comment]
Closed as this feature was removed
