### ISSUE TITLE
Fehler in Nether und end

### ISSUE THREAD

**Issue by Pinkglitter2216** [CzechPMDevs/MultiWorld#238]
- Issue Description: Wenn man in den nether oder das end joint, spawnt man unter dem bedrock und stirbt. Wenn man dann im nether versucht Blöcke abzubauen, werden diese zu bedrock und im end kann man gar keine Blöcke abbauen.

- Version: 1.6.0 beta-6

- Server Version: Pocketmine MP 3.26.1 für 1.18

- Crashdump, backtrace or other files:
![Filme   TV 07 12 2021 18_26_38](https://user-images.githubusercontent.com/68972311/145077202-133e08c3-6095-4477-82e5-d2685c90e565.png)

**Comment by MonoAdrian23** [comment]
Pocketmine 3 ist veraltet.
Außerdem existiert die Issue bereits!

**Comment by Pinkglitter2216** [comment]
Das tut mir leid, ich hatte die existierende Ausgabe nicht gesehen. Auch wenn pocketmine 3 veraltet ist, gibt es noch genug Server die auf dieser Version laufen. Und es wird mit Sicherheit auch noch eine Zeit lang dauern bis alle auf Pocketmine 4 updaten können.

**Comment by MonoAdrian23** [comment]
Wenn man noch Pocketmine 3 nutzt ist das die Schuld der Serverinhaber.
Man sollte endlich begreifen das der Support dafür eingestellt wird.

**Comment by Pinkglitter2216** [comment]
Ich habe eine einfache Frage gestellt und kann nicht verstehen warum sie gleich so unfreundlich reagieren. Gut zu wissen, dann stellt man besser in Zukunft keine Fragen mehr

**Comment by MonoAdrian23** [comment]
Ich habe nicht unfreundlich reagiert sondern Fakten genannt.
Und die meisten Pocketmine Server haben bereits auf API 4 umgestellt.
Das kleine Server noch auf der 3 bleiben wird wohl daran liegen dass sie keine Ahnung haben wie man Plugins auf die API 4 umschreibt.
Wie gesagt, Pocketmine 3 ist Geschichte.
Updaten oder mit dem Fehler leben.

**Comment by VixikHD** [comment]
Duplicate #237
