### ISSUE TITLE
Generator is not optional on mw create

### ISSUE THREAD

**Issue by fuyutsuki** [CzechPMDevs/MultiWorld#240]
- Issue Description:
Generator is not optional on `/mw create`, but README shows generator as optional
https://github.com/CzechPMDevs/MultiWorld/blob/af1b85656a05ef927f8c67de4d9d86baa13e6509/README.md?plain=1#L101

- Version:
DevTools v1.15.0, MultiWorld v1.7.0-beta3

- Server Version: 
4.0.0 (git hash: 468faa464b2bc5c97f23fafbb71ea61035f6f218)

- Crashdump, backtrace or other files:
```bash
mw create test
[13:38:26.069] [Server thread/INFO]: Generator  not found.
```

**Comment by VixikHD** [comment]
Fixed in https://github.com/CzechPMDevs/MultiWorld/commit/5cb329272dd0e61c7a07a01fc7fc73c4aad202de
