### ISSUE TITLE
the game crashes when using the generator Custom (mw_normal)

### ISSUE THREAD

**Issue by zpwrd** [CzechPMDevs/MultiWorld#242]
- Issue Description: When you create a new world with a Custom generator and teleport to it, the game client freezes and it crashes, and the server disconnects the player due to a timeout. Used command to generate new world: /mw create test 0 custom

- Version: last

- Server Version: 4.0.0

- Crashdump, backtrace or other files: none

**Comment by VixikHD** [comment]
Without knowing your Plugin version, OS, PHP, Client version, other plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

**Comment by zpwrd** [comment]
The plugin version is 1.7.0 beta3. this is obvious if a new version of pmmp has been released I am using client version 1.18.0 with pmmp kernel 4.0.0. other plugins are missing, except for devtools. I have already described in the ticket how the problem arises.
