### ISSUE TITLE
End/Nether generation Error

### ISSUE THREAD

**Issue by DragonfireHD** [CzechPMDevs/MultiWorld#243]
- Issue Description:
- [22:06:13.716] [Server thread/CRITICAL]: Could not execute asynchronous task PopulationTask: Task crashed

[22:06:13.787] [Server thread/CRITICAL]: Could not execute asynchronous task PopulationTask: Task crashed

[22:06:13.790] [AsyncWorker#20 thread/CRITICAL]: DivisionByZeroError: "Division by zero" (EXCEPTION) in "/home/minecraft/plugins/MultiWorld_dev-240.phar/src/czechpmdevs/multiworld/generator/nether/populator/Ore" at line 63

--- Stack trace ---

#0 /home/minecraft/plugins/MultiWorld_dev-240.phar/src/czechpmdevs/multiworld/generator/nether/populator/Ore(46): czechpmdevs\multiworld\generator\nether\populator\Ore->placeObject(object pocketmine\world\generator\object\OreType#79677, object pocketmine\utils\Random#79458, object pocketmine\world\SimpleChunkManager#75868, integer 304, integer 90, integer 359)

#1 /home/minecraft/plugins/MultiWorld_dev-240.phar/src/czechpmdevs/multiworld/generator/nether/NetherGenerator(119): czechpmdevs\multiworld\generator\nether\populator\Ore->populate(object pocketmine\world\SimpleChunkManager#75868, integer 19, integer 22, object pocketmine\utils\Random#79458)

#2 pmsrc/src/world/generator/PopulationTask(98): czechpmdevs\multiworld\generator\nether\NetherGenerator->populateChunk(object pocketmine\world\SimpleChunkManager#75868, integer 19, integer 22)

#3 pmsrc/src/scheduler/AsyncTask(84): pocketmine\world\generator\PopulationTask->onRun()

#4 (): pocketmine\scheduler\AsyncTask->run()

- Version: 1.7.0-beta3

- Server Version:
- PHP: 8.0.13
- Version: 1.18.0
- Mc-protocol: 475

**Comment by VixikHD** [comment]
Duplicate #241, already fixed
