### ISSUE TITLE
Form Crash and world file missing

### ISSUE THREAD

**Issue by DragonfireHD** [CzechPMDevs/MultiWorld#245]
- Issue Description:
- [03:30:29.278] [Server thread/CRITICAL]: Error: "Class "czechpmdevs\libpmform\type\SimpleForm" not found" (EXCEPTION) in "plugins/MultiWorld.4.0.phar/src/czechpmdevs/multiworld/command/subcommand/ManageSubCommand" at line 56

--- Stack trace ---

#0 plugins/MultiWorld.4.0.phar/src/czechpmdevs/multiworld/command/MultiWorldCommand(98): czechpmdevs\multiworld\command\subcommand\ManageSubCommand->execute(object pocketmine\player\Player#98976, array[0], string[6] manage)

#1

And the End world
He say to me the generator End dosent exist i cant generate a End World

- Version: 1.7.0-beta4

- Server Version: 8.0.13/ version 1.18.0

- Crashdump, backtrace or other files:

**Comment by VixikHD** [comment]
Building plugin with updated build script should work now.
