### ISSUE TITLE
Carve generation is incosistent in CustomGenerator

### ISSUE THREAD

**Issue by VixikHD** [CzechPMDevs/MultiWorld#246]
- Issue Description: Carves are generated wrong

- Version: 1.3.x

- Server Version: 4.0.4

- Crashdump, backtrace or other files:
![image](https://user-images.githubusercontent.com/40556088/146544812-81d2d147-614e-4dca-ac04-1cfb704b5a57.png)

**Comment by DragonfireHD** [comment]
![Screenshot_20211219-184703_Minecraft](https://user-images.githubusercontent.com/50929188/146685230-1337824b-7615-4a4a-9bc4-eebbe4d88bd7.png)


The End Sun is very End full xD

**Comment by VixikHD** [comment]
> ![Screenshot_20211219-184703_Minecraft](https://user-images.githubusercontent.com/50929188/146685230-1337824b-7615-4a4a-9bc4-eebbe4d88bd7.png)
> 
> The End Sun is very End full xD

#237
