### ISSUE TITLE
Nether and End World doenst Work

### ISSUE THREAD

**Issue by MonoAdrian23** [CzechPMDevs/MultiWorld#247]
- Issue Description:
-  I have created a Nether and End World, but the Game freezes.
- It happens with Handle Dimensions False and True

- Version: Dev 242

- Server Version: PM 4.0.3

- Crashdump, backtrace or other files:
- pmsrc/src/world/format/io/data/BedrockWorldData(169): pocketmine\utils\Filesystem::safeFilePutContents(string[42] /home/minecraft/worlds/..7Nether/level.dat, string[535] ..............DayCycleStopTime.......Difficulty.......ForceGameType....GameType.)
#1 pmsrc/src/world/World(1153): pocketmine\world\format\io\data\BedrockWorldData->save()
#2 pmsrc/src/command/defaults/SaveCommand(56): pocketmine\world\World->save(true)
#3 pmsrc/src/command/SimpleCommandMap(220): pocketmine\command\defaults\SaveCommand->execute(object pocketmine\console\ConsoleCommandSender#25414, string[8] save-all, array[0])
#4 pmsrc/src/Server(1406): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\console\ConsoleCommandSender#25414, string[8] save-all)
#5 pmsrc/src/Server(1038): pocketmine\Server->dispatchCommand(object pocketmine\console\ConsoleCommandSender#25414, string[8] save-all)
#6 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\Server->pocketmine\{closure}()
#7 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
#8 pmsrc/src/Server(1657): pocketmine\snooze\SleeperHandler->sleepUntil(double 1639753173.2082)
#9 pmsrc/src/Server(1044): pocketmine\Server->tickProcessor()
#10 pmsrc/src/PocketMine(303): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/minecraft/, string[24] /home/minecraft/plugins/)
#11 pmsrc/src/PocketMine(326): pocketmine\server()
#12 pmsrc(11): require(string[57] phar:///home/minecraft/pocketmine.phar/src/PocketMine.php)

PocketMine-MP version: 4.0.3 [Protocol 475]
Git commit: 795ebd182461f96beeb47b067f7fe33e76bc9059
uname -a: Linux d2779e7c13f3 5.14.0-0.bpo.2-amd64 #1 SMP Debian 5.14.9-2~bpo11+1 (2021-10-10) x86_64
PHP Version: 8.0.13
Zend version: 4.0.13
OS: Linux, linux
Composer libraries: 
- adhocore/json-comment 1.1.2@fc2f76979f0a44a5f5bc2a2b600d0762fe0e78e7
- brick/math 0.9.3@ca57d18f028f84f777b2168cd1911b0dee2343ae
- daverandom/callback-validator unknown@unknown
- fgrosse/phpasn1 v2.4.0@eef488991d53e58e60c9554b09b1201ca5ba9296
- netresearch/jsonmapper v4.0.0@8bbc021a8edb2e4a7ea2f8ad4fa9ec9dce2fcb8d
- pocketmine/bedrock-data 1.5.0+bedrock-1.18.0@482c679aa5ed0b81c088c2b1ff0b8110a94c8a6c
- pocketmine/bedrock-protocol 7.1.0+bedrock-1.18.0@42f2a00634c17c346fd98c05b2daf29d1fbf5805
- pocketmine/binaryutils 0.2.3@dc94786fc6c30012b1892f548dbb8a8c9c0a8cd9
- pocketmine/callback-validator 1.0.3@64787469766bcaa7e5885242e85c23c25e8c55a2
- pocketmine/classloader 0.2.0@49ea303993efdfb39cd302e2156d50aa78209e78
- pocketmine/color 0.2.0@09be6ea6d76f2e33d6813c39d29c22c46c17e1d2
- pocketmine/errorhandler 0.3.0@ec742b209e8056bbe855069c4eff94c9734ea19b
- pocketmine/locale-data 2.2.0@dc88ad618a482e55b7c9fec162257efa62a67d6f
- pocketmine/log 0.4.0@e6c912c0f9055c81d23108ec2d179b96f404c043
- pocketmine/log-pthreads 0.4.0@61f709e8cf36bcc24e4efe02acded680a1ce23cd
- pocketmine/math 0.4.2@aacc3759a508a69dfa5bc4dfa770ab733c5c94bf
- pocketmine/nbt 0.3.2@3e0d9ef6b6c5fb45e3745a121296e75631b3eefe
- pocketmine/pocketmine-mp 4.0.3@795ebd182461f96beeb47b067f7fe33e76bc9059
- pocketmine/raklib 0.14.2@e3a861187470e1facc6625040128f447ebbcbaec
- pocketmine/raklib-ipc 0.1.1@922a6444b0c6c7daaa5aa5a832107e1ec4738aed
- pocketmine/snooze 0.3.1@0ac8fc2a781c419a1f64ebca4d5835028f59e29b
- ramsey/collection 1.2.2@cccc74ee5e328031b15640b51056ee8d3bb66c0a
- ramsey/uuid 4.2.3@fc9bb7fb5388691fd7373cd44dcb4d63bbcf24df
- rhumsaa/uuid unknown@unknown
- symfony/polyfill-ctype v1.23.0@46cd95797e9df938fdd2b03693b5fca5e64b01ce
- symfony/polyfill-php80 v1.23.1@1100343ed1a92e3a38f9ae122fc0eb21602547be
- symfony/polyfill-php81 v1.23.0@e66119f3de95efc359483f810c4c3e6436279436
- webmozart/assert 1.10.0@6964c76c7804814a842473e0c8fd15bab0f18e25
- webmozart/path-util 2.3.0@d939f7edc24c9a1bb9c0dee5cb05d8e859490725

Loaded plugins:
BetterBan 4.0.1 by supercrfafter333 for API(s) 4.0.0
BetterFlight 1.0.0, MyPlot 2.0.0, Multiworld

**Comment by MonoAdrian23** [comment]
![Screenshot_2021-12-17-16-07-54-81_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/59027482/146566314-99bf77dd-67ae-4c82-a73d-574255d7dcf0.jpg)

**Comment by VixikHD** [comment]
Duplicate #241, already fixed. Try using newer dev build.

**Comment by MonoAdrian23** [comment]
Latest Dev Build is 242
And i use 242

**Comment by MonoAdrian23** [comment]
You should read my issue Complete 
From Top to Bottom.
Its Dev 242 and IT isnt fixed 😭😘

**Comment by VixikHD** [comment]
Try the newest one dev build. Ender generator might have not work with some seeds, but the nether one should work.

**Comment by VixikHD** [comment]
Dev 243 should work fine

**Comment by MonoAdrian23** [comment]
OK i try

**Comment by MonoAdrian23** [comment]
But 243 isnt available on Dev Builds

**Comment by VixikHD** [comment]
I am really sorry, it's fixed. Poggit somehow disabled CI on this repo.

**Comment by MonoAdrian23** [comment]
Oh ok.
No Problem.
Thank you very much for youre hard Work.
I Hope Emeralds, Pumpkins and Melons is on TODO List.
Because this Plugin is great.
Have a Nice Day 🥰

**Comment by MonoAdrian23** [comment]
It workes now
Thank you very much
