### ISSUE TITLE
Nether in Pocketmine 4 is very dark

### ISSUE THREAD

**Issue by PocketMiner92** [CzechPMDevs/MultiWorld#249]
This isnt normal.
![Screenshot_2021-12-18-10-48-47-55_5c8300b655012b1930f2e0a7b81bf6a9.jpg](https://user-images.githubusercontent.com/96331694/146637067-950493a5-9262-4893-b49f-ed841b434ca1.jpg)

**Comment by PocketMiner92** [comment]
Pocketmine 4.0.3
Multiworld Dev 243
Minecraft BE Android

**Comment by VixikHD** [comment]
It's caused by missing api in server software. Check #237

**Comment by PocketMiner92** [comment]
OK thank you very much and have a Nice Day
