### ISSUE TITLE
Normal Players Not Being Able To TP to world.. :(

### ISSUE THREAD

**Issue by joshuasing** [CzechPMDevs/MultiWorld#25]
- Issue Description: 
on my server i have A ton of games but each game is in a different world.
i use the plugin: Slapper to tp players to the other worlds but when a non OP player clicks on a slapper that runs /mw tp WORLDNAMEHERE it says you do not have perms to use this command.

- Version: 1.4.3

- Server Version: 3.1.0

- Crashdump, backtrace or other files: 
N/A

**Comment by GamakCZ** [comment]
Slapper can run command /mw tp WORLDNAMEHERE <player>
