### ISSUE TITLE
Deepslate and other Stuff (Feature Request)

### ISSUE THREAD

**Issue by PocketMiner92** [CzechPMDevs/MultiWorld#252]
- Feature Description:
- Add all new Blocks for Overworld and Dimensions because PM4 now Support this Blocks.

- Version:

- Server Version:

- Crashdump, backtrace or other files:

**Comment by VixikHD** [comment]
Deepslate is not supported by pm4. Neither dimensions aren't. That means I am not able to implement those for now.
