### ISSUE TITLE
RandomTickSpeed Bug

### ISSUE THREAD

**Issue by iMqrc** [CzechPMDevs/MultiWorld#253]
- Issue Description:   If I try to set the world’s tickspeed to 0, server will crash

- Version: MultiWorld v1.7.0-beta4

- Server Version: 4.0.5

- Crashdump, backtrace or other files: https://cdn.discordapp.com/attachments/924264721958445066/929006935951429693/Fri_Jan_7-12.55.04-UTC_2022.log

**Comment by VixikHD** [comment]
Thank you for bug report! Sounds like an [XY problem](https://xyproblem.info/) (There may be more ways to fix your problem different way -> You should have send more information, eg. why do you want to change tick) Also I am not able to open crashdump you sent. Consider using [pmmp crash archive](https://crash.pmmp.io/).
