### ISSUE TITLE
Perm Bug

### ISSUE THREAD

**Issue by Sleak101** [CzechPMDevs/MultiWorld#254]
**The perms don't work.**

**Comment by VixikHD** [comment]
Without several required information issue cannot begin to be solved. Pre-formatted template for issue is available when creating the issue. I am gonna leave the issue closed untill this template is gonna be used.

**Comment by Sleak101** [comment]
Sooo, it's gonna be fixed? I had no idea what you said ;-;

**Comment by VixikHD** [comment]
It's not gonna be fixed. The issue is missing information such as plugin version, server version, os, ...
