### ISSUE TITLE
/mw list crash the Server

### ISSUE THREAD

**Issue by PocketMiner92** [CzechPMDevs/MultiWorld#257]
**Describe the bug**

**To Reproduce**
1. Type /mw list
2. Server crashed

**Expected behavior**
Type /mw list, and Server is crashing

[Wed_Jan_19-10.35.25-CET_2022.log](https://github.com/CzechPMDevs/MultiWorld/files/7895985/Wed_Jan_19-10.35.25-CET_2022.log)

**Screenshots**

**System information (please complete the following information):**
- OS: [linux]
- php version [8.0.13]
- Multiworld Dev 246

**Additional context**

**Comment by PocketMiner92** [comment]
???

**Comment by keenanyafiqy** [comment]
You shouldn't use the development version!
It is under development. And it is not stable!

**Comment by keenanyafiqy** [comment]
Use the stable version instead.
Maybe you'll using a development version because want to know the new features in there.

**Comment by PocketMiner92** [comment]
I use Dev Version for Testing Bugs.
Without any Testing, No stable Version can created

**Comment by VixikHD** [comment]
Fixed in latest dev build
