### ISSUE TITLE
Please add the level.dat update feature to the world

### ISSUE THREAD

**Issue by soiconpocketmine** [CzechPMDevs/MultiWorld#26]
- Issue Description:

- Version:

- Server Version:

- Crashdump, backtrace or other files:

**Comment by GamakCZ** [comment]
We need more information

**Comment by GamakCZ** [comment]
You want to add commands to manage with level.dat?

**Comment by GamakCZ** [comment]
Closed due to inactivity

**Comment by lcyLand** [comment]
You can use [NBTExplorer](https://github.com/jaquadro/NBTExplorer) and then go to your worlds folder, open the level.dat and change basically anything you want...
