### ISSUE TITLE
Add usage to `/mw` so that EasyCommandAutofil can work with it

### ISSUE THREAD

**Issue by Swift-Strider** [CzechPMDevs/MultiWorld#260]
## Problem
When using EasyCommandAutofill, I don't get autofill for `/mw`

## Solution
I would like usage, one that EasyCommandAutofill can parse, to be added to the `/mw` command

**Comment by VixikHD** [comment]
resolved in 2.0

**Comment by Swift-Strider** [comment]
Thank you for looking into this. :)
