### ISSUE TITLE
cant support simplenpc 

### ISSUE THREAD

**Issue by Prex9090** [CzechPMDevs/MultiWorld#269]
hello im owner of a server. my report is cant tp to the command i added like "mw tp (worlname)" cant connect when i click my npc plugins. its clickable and not working. if i use command /mw tp (worldname) its working. the npc was succesfully working. i think the multiworld. thanks. my console  said "[MultiWorld] Unable to enable dimensions handling (https://github.com/CzechPMDevs/MultiWorld/issues/237)"

**Comment by VixikHD** [comment]
Check #237, you can find more information regarding to the topic of dimensions handling there.
