### ISSUE TITLE
Minecraft basic for pocketmine 4.0.0

### ISSUE THREAD

**Issue by Willtom999** [CzechPMDevs/MultiWorld#270]
add the basic nether biomes of minecraft with the Inether plugin which adds the blocks and also add the normal world biome of basic Minecraft in generator

**Comment by PocketMiner92** [comment]
Use PowernukkitX and you have all 1.18+ features.
Pocketmine is Not good

**Comment by Willtom999** [comment]
:/

**Comment by VixikHD** [comment]
Custom generator != vanilla generator, so does not expect vanilla features. Most of these cannot be even handled by PocketMine

**Comment by PocketMiner92** [comment]
No professionell Server use Pocketmine
You should use Powernukkit or PowernukkitX.
Its possible with Both Softwares

**Comment by VixikHD** [comment]
That is irrelevant
