### ISSUE TITLE
crashed

### ISSUE THREAD

**Issue by Dasupergrasskakjd** [CzechPMDevs/MultiWorld#274]
it crashed when i try to use /mw unload <default world> when i think it should only make fail to use the command but it crashed
[log](https://mclo.gs/YARl3xf)

**Comment by VixikHD** [comment]
It is not possible to unload default world

**Comment by VixikHD** [comment]
This bug was already fixed in c6be60b08f89d91baa02aec149203a693b73c0e0 (duplicate #259). A new release for poggit is waiting approval.
