### ISSUE TITLE
Bug Cause: Please remove the game rules. No game rules required.

### ISSUE THREAD

**Issue by gamegam** [CzechPMDevs/MultiWorld#276]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
- OS: [e.g. linux]
- PHP Version: [e.g. 8.0]
- MultiWorld Version: [e.g. dev#142, Release 1.7.0-beta2]

**Additional context**

**Comment by VixikHD** [comment]
removed
