### ISSUE TITLE
error ...

### ISSUE THREAD

**Issue by gamegam** [CzechPMDevs/MultiWorld#277]
4:23:38.635] [Server thread/CRITICAL]: LogicException: "Requested unknown rule doMobSpawning" (EXCEPTION) in "plugins/MultiWorld-60c4346b15c1a138d6e14f55d27648d8d45afeb0/src/czechpmdevs/multiworld/world/gamerules/GameRule" at line 144
--- Stack trace ---
  #0 plugins/MultiWorld-60c4346b15c1a138d6e14f55d27648d8d45afeb0/src/czechpmdevs/multiworld/world/gamerules/GameRules(142): czechpmdevs\multiworld\world\gamerules\GameRule::fromRuleName(string[13] doMobSpawning)
  #1 plugins/MultiWorld-60c4346b15c1a138d6e14f55d27648d8d45afeb0/src/czechpmdevs/multiworld/world/gamerules/GameRules(100): czechpmdevs\multiworld\world\gamerules\GameRules::unserializeGameRules(object pocketmine\nbt\tag\CompoundTag#108481)
  #2 plugins/MultiWorld-60c4346b15c1a138d6e14f55d27648d8d45afeb0/src/czechpmdevs/multiworld/MultiWorld(87): czechpmdevs\multiworld\world\gamerules\GameRules::loadFromWorld(object pocketmine\world\World#108240)
  #3 plugins/MultiWorld-60c4346b15c1a138d6e14f55d27648d8d45afeb0/src/czechpmdevs/multiworld/EventListener(65): czechpmdevs\multiworld\MultiWorld::getGameRules(object pocketmine\world\World#108240)
  #4 pmsrc/src/event/RegisteredListener(60): czechpmdevs\multiworld\EventListener->onJoin(object pocketmine\event\player\PlayerJoinEvent#137287)
  #5 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerJoinEvent#137287)
  #6 pmsrc/src/player/Player(834): pocketmine\event\Event->call()
  #7 pmsrc/src/network/mcpe/NetworkSession(704): pocketmine\player\Player->doFirstSpawn()
  #8 pmsrc/src/network/mcpe/NetworkSession(697): pocketmine\network\mcpe\NetworkSession->onClientSpawnResponse()
  #9 pmsrc/src/network/mcpe/handler/SpawnResponsePacketHandler(35): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
  #10 pmsrc/vendor/pocketmine/bedrock-protocol/src/SetLocalPlayerAsInitializedPacket(42): pocketmine\network\mcpe\handler\SpawnResponsePacketHandler->handleSetLocalPlayerAsInitialized(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket#137143)
  #11 pmsrc/src/network/mcpe/NetworkSession(388): pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket->handle(object pocketmine\network\mcpe\handler\SpawnResponsePacketHandler#97386)
  #12 pmsrc/src/network/mcpe/NetworkSession(351): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket#137143, string[2] q.)
  #13 pmsrc/src/network/mcpe/raklib/RakLibInterface(182): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[43] c*d4......v.rdh.v9...#...#.P..gdb2.q.&,....)
  #14 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[52] ...q......; C..4..g.E....A....c.......f.|..~...CL..N)
  #15 pmsrc/src/network/mcpe/raklib/RakLibInterface(112): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#102325)
  #16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #17 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #18 pmsrc/src/Server(1703): pocketmine\snooze\SleeperHandler->sleepUntil(float 1656015818.653)
  #19 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
  #20 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[38] C:\Users\Administrator\Desktop\server\, string[46] C:\Users\Administrator\Desktop\server\plugins\)
  #21 pmsrc/src/PocketMine(327): pocketmine\server()
  #22 pmsrc(11): require(string[82] phar://C:/Users/Administrator/Desktop/server/PocketMine-MP.phar/src/PocketMine.p)
--- End of exception information ---
[04:23:38.636] [Server thread/EMERGENCY]: 복구 불가능한 오류가 발생하여 서버가 충돌했습니다. 충돌 덤프를 만듭니다
[04:23:38.647] [Server thread/EMERGENCY]: "C:/Users/Administrator/Desktop/server/crashdumps/Fri_Jun_24-05.23.38-KST_2022.log" 파일을 충돌 보관소에 업로드하고 버그 보고 페이지에 링크를 제출해주세요. 가능한 한 많은 정보를 주시기 바랍니다.
[04:23:38.647] [Server thread/EMERGENCY]: Forcing server shutdown

**Comment by VixikHD** [comment]
resolved in 2.0
