### ISSUE TITLE
end generation 

### ISSUE THREAD

**Issue by TheLemzz** [CzechPMDevs/MultiWorld#278]
end world generation is not generated correctly. when you create an end world, only one island appears and no more. On PM3 this problem was solved by flying forward and finding other islands, which were generated correctly, but in PM4 I could not find any island. 

**Screenshots**

**System information (please complete the following information):**
- OS: [e.g. linux]
- PHP Version: [e.g. 8.0]
- MultiWorld Version: [e.g. dev#142, Release 1.7.0-beta2]

**Comment by TheLemzz** [comment]
![Screenshot_20220628-154923](https://user-images.githubusercontent.com/75723466/176183309-1c1c2277-0bea-47a8-a072-6756f05da459.jpg)

**Comment by TheLemzz** [comment]
I wait

**Comment by TheLemzz** [comment]
Pls No throwing this plugin =)

**Comment by MonoAdrian23** [comment]
Only Idiots using Pocketmine
PowernukkitX is fully Vanilla and more Plugin Support.

**Comment by TheLemzz** [comment]
I agree, but I already run a fairly large project on PocketMine-MP, and obviously I need time to move to another kernel. I'm not going to abandon the project while I'm migrating the whole build. I plan to use JAVA kernel in conjunction with GEYSERMC.

**Comment by MonoAdrian23** [comment]
GeyserMC is full of bugs!
No one use this.

**Comment by TheLemzz** [comment]
And what is an adequate replacement for Geysermc?

**Comment by TheLemzz** [comment]
Accidentally

**Comment by MonoAdrian23** [comment]
Its Not possible to Connect Bedrock and Java without thousands of bugs.
You should choose Bedrock or Java for a perfect Server.
And Bedrock haves PowernukkitX.
This is full time developed and perfect for all types of Servers.
Java haves PaperMC.
But Java is loosing many users.
Never use Geyser or another stupid Bridge.
This is why the Minecraft Users leave many Servers.

**Comment by TheLemzz** [comment]
> Its Not possible to Connect Bedrock and Java without thousands of bugs. You should choose Bedrock or Java for a perfect Server. And Bedrock haves PowernukkitX. This is full time developed and perfect for all types of Servers. Java haves PaperMC. But Java is loosing many users. Never use Geyser or another stupid Bridge. This is why the Minecraft Users leave many Servers.

How does a geyser have bugs for example? I only noticed a bug with the sound of breaking occasionally. JAVA still has a lot of players as for me.

**Comment by nebotLol** [comment]
Test

**Comment by VixikHD** [comment]
Fixed in https://github.com/CzechPMDevs/MultiWorld/commit/670e31cd74ab1fdf82b0ef5d759b67ffb966a853
