### ISSUE TITLE
PM5

### ISSUE THREAD

**Issue by TheLemzz** [CzechPMDevs/MultiWorld#279]
Hi! What about update this plugin to PM5? Would this cool 😎

**Comment by VixikHD** [comment]
There's a new branch [api/pm5](https://github.com/CzechPMDevs/MultiWorld/tree/api/pm5) by @supercrafter333. You can try out latest dev build, which can be found on [poggit](https://poggit.pmmp.io/r/185568/MultiWorld_dev-257.phar).
