### ISSUE TITLE
Server crash when creating world

### ISSUE THREAD

**Issue by nickalyn** [CzechPMDevs/MultiWorld#29]
- Issue Description:I’m running a server from plug for Pocketmine and when I try to make a world it crashes I enter this command /mw create Test7 Flat.Once I send the command it crashes.

- Version:v1.5.0

- Server Version:1.7

- Crashdump, backtrace or other files:
Can I send your a screen shot or via email or discord?since I can’t copy and paste it?

**Comment by GamakCZ** [comment]
I need more information to fix it. So can you send me crashdump file here?

**Comment by lcyLand** [comment]
BACKSTORY:
He was reporting it happening on the phone version, NOT the pc version, the problem with this is plugplugin. So just so you know, it seems to not be working ALL BECAUSE OF THAT PLUGIN, kthxbai

**Comment by lcyLand** [comment]
guys close this

**Comment by nickalyn** [comment]
he gives me all his emails/passwords, lol, so I closed it anyway
