### ISSUE TITLE
World teleport loading screen

### ISSUE THREAD

**Issue by BananaGER** [CzechPMDevs/MultiWorld#290]
**Describe the bug**
I dont know is it a bug or not but past 2020 it had say if you changed the world "Loading Terrain" or something but now its not saying that the Terrain is loading can i activate this again because when i teleport, in the world you can see chunks from the other world for a few seconds

**Expected behavior**
I expect that there is the default minecraft Building Terrain Loading Screen

**System information (please complete the following information):**
- OS: i dont know i host from Zap Hosting but i think Linux
- PHP Version: the latest
- MultiWorld Version: dev#271

**Comment by VixikHD** [comment]
It is not possible to activate this feature for now.

**Comment by VixikHD** [comment]
This should be implemented in independent plugin on MultiWorld.
