### ISSUE TITLE
Error while executing the /mw manage command

### ISSUE THREAD

**Issue by RemBog** [CzechPMDevs/MultiWorld#291]
Error: During inheritance of JsonSerializable: Uncaught ErrorException: Return type of czechpmdevs\multiworld\libs\czechpmdevs\libpmform\Form::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/container/plugins/MultiWorld_2 (1).phar/src/czechpmdevs/multiworld/libs/czechpmdevs/libpmform/Form.php:75
File: plugins/MultiWorld_2 (1).phar/src/czechpmdevs/multiworld/libs/czechpmdevs/libpmform/Form

**Comment by dadodasyra** [comment]
This is related to PHP 8.1 since jsonSerializable objects now requires to return mixed instead of nothing on jsonSerialize function.
Therefore "libpmform" is not this repository but on https://github.com/CzechPMDevs/libpmform

**Comment by VixikHD** [comment]
We don't support php 8.0 nor PM4 anymore. I'd recommend to switch to PM5 along with php 8.1
