### ISSUE TITLE
Alias "vanilla_nether" is already assigned on PocketMine-MP 5.1.2 API

### ISSUE THREAD

**Issue by XackiGiFF** [CzechPMDevs/MultiWorld#294]
**Describe the bug**
I have crash when use MultiWorld with other plugin [Muqsit](https://github.com/Muqsit)/[VanillaGenerator](https://github.com/Muqsit/VanillaGenerator) for add custom generators.

**To Reproduce**
1. Add MultiWorld and VanillaGenerator (from pm5)
2. Reload server
3. See error

**Expected behavior**
Add custom generators without error, MultiWorld have own individual names for world generators.

**Screenshots**
VanillaGenerator, class Loader (register generators):
![image](https://github.com/CzechPMDevs/MultiWorld/assets/29034010/d7876520-7a04-4ab8-83fd-ca94843bb40d)
MultiWorld, class MultiWorld (register generators):
![image](https://github.com/CzechPMDevs/MultiWorld/assets/29034010/c3ea6a73-e236-4631-8569-c0870f1a2502)
Crash message:
![image](https://github.com/CzechPMDevs/MultiWorld/assets/29034010/a741ed6b-9b38-4009-ab4c-332bd8d9dc00)

**System information:**
- OS: [linux]
- PHP Version: [8.2.6]
- MultiWorld Version: [dev [#276](https://poggit.pmmp.io/ci/CzechPMDevs/MultiWorld/MultiWorld/276), MultiWorld v2.1.0-beta2]
- VanillaGenerator Version: [dev [#64](https://poggit.pmmp.io/babs/25feb), VanillaGenerator v0.0.4]

**Additional context**
I think needs add individual names for MultiWorlds generators. Today just rename vanilla_nether to custom_vanilla_nether works for me...
.

**Comment by VixikHD** [comment]
vanilla_nether is actually Muqsit's nether generator shipped from virion

**Comment by VixikHD** [comment]
You don't need to add it Muqsit's VanillaGenerator in order to generate world with it, when you have already loaded it with MultiWorld.
