### ISSUE TITLE
MultiWorld Crash after latest updates

### ISSUE THREAD

**Issue by n00bslayr94** [CzechPMDevs/MultiWorld#295]
**Describe the bug**
A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: MultiWorld

Error: Call to a member function getParameters() on array
File: pmsrc/vendor/pocketmine/bedrock-protocol/src/AvailableCommandsPacket
Line: 533
Type: Error

[533] 				foreach($overload->getParameters() as $parameter){

**To Reproduce**
1. Update to v1.20.1 MC, PM 5.3.0.
2. Launch game.
3. Experience Crash

**Expected behavior**
Game should launch as expected.

**System information (please complete the following information):**
- Linux
- PHP Version: 8.2
- MultiWorld Version: [e.g. dev#276, Release 2.1.0-beta2]

**Comment by CoolCuzzy** [comment]
Yes this occured for me aswell, need a fix asap!

**Comment by CoolCuzzy** [comment]
here is the error in my server:
2.197] [Server thread/CRITICAL]: Error: "Call to a member function getParameters() on array" (EXCEPTION) in "pmsrc/vendor/pocketmine/bedrock-protocol/src/AvailableCommandsPacket" at line 533
--- Stack trace ---
  #0 pmsrc/vendor/pocketmine/bedrock-protocol/src/DataPacket(84): pocketmine\network\mcpe\protocol\AvailableCommandsPacket->encodePayload(object pocketmine\network\mcpe\protocol\serializer\PacketSerializer#108206)
  #1 pmsrc/src/network/mcpe/NetworkSession(489): pocketmine\network\mcpe\protocol\DataPacket->encode(object pocketmine\network\mcpe\protocol\serializer\PacketSerializer#108206)
  #2 pmsrc/src/network/mcpe/NetworkSession(470): pocketmine\network\mcpe\NetworkSession::encodePacketTimed(object pocketmine\network\mcpe\protocol\serializer\PacketSerializer#108206, object pocketmine\network\mcpe\protocol\AvailableCommandsPacket#176998)
  #3 plugins/RankSystem.phar/src/IvanCraft623/RankSystem/libs/CortexPE/Commando/PacketHooker(81): pocketmine\network\mcpe\NetworkSession->sendDataPacket(object pocketmine\network\mcpe\protocol\AvailableCommandsPacket#176998)
  #4 plugins/RankSystem.phar/src/IvanCraft623/RankSystem/libs/CortexPE/Commando/libs/muqsit/simplepackethandler/interceptor/PacketInterceptorListener(83): IvanCraft623\RankSystem\libs\CortexPE\Commando\PacketHooker::IvanCraft623\RankSystem\libs\CortexPE\Commando\{closure}(object pocketmine\network\mcpe\protocol\AvailableCommandsPacket#176998, object pocketmine\network\mcpe\NetworkSession#142053)
  #5 pmsrc/src/event/RegisteredListener(61): IvanCraft623\RankSystem\libs\CortexPE\Commando\libs\muqsit\simplepackethandler\interceptor\PacketInterceptorListener->IvanCraft623\RankSystem\libs\CortexPE\Commando\libs\muqsit\simplepackethandler\interceptor\{closure}(object pocketmine\event\server\DataPacketSendEvent#108252)
  #6 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketSendEvent#108252)
  #7 pmsrc/src/network/mcpe/NetworkSession(463): pocketmine\event\Event->call()
  #8 plugins/MultiWorld.phar/src/czechpmdevs/multiworld/libs/CortexPE/Commando/PacketHooker(81): pocketmine\network\mcpe\NetworkSession->sendDataPacket(object pocketmine\network\mcpe\protocol\AvailableCommandsPacket#176998)
  #9 plugins/MultiWorld.phar/src/czechpmdevs/multiworld/libs/CortexPE/Commando/libs/muqsit/simplepackethandler/interceptor/PacketInterceptorListener(81): czechpmdevs\multiworld\libs\CortexPE\Commando\PacketHooker::czechpmdevs\multiworld\libs\CortexPE\Commando\{closure}(object pocketmine\network\mcpe\protocol\AvailableCommandsPacket#176998, object pocketmine\network\mcpe\NetworkSession#142053)
  #10 pmsrc/src/event/RegisteredListener(61): czechpmdevs\multiworld\libs\CortexPE\Commando\libs\muqsit\simplepackethandler\interceptor\PacketInterceptorListener->czechpmdevs\multiworld\libs\CortexPE\Commando\libs\muqsit\simplepackethandler\interceptor\{closure}(object pocketmine\event\server\DataPacketSendEvent#108199)
  #11 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketSendEvent#108199)
  #12 pmsrc/src/network/mcpe/NetworkSession(463): pocketmine\event\Event->call()
  #13 pmsrc/src/network/mcpe/NetworkSession(997): pocketmine\network\mcpe\NetworkSession->sendDataPacket(object pocketmine\network\mcpe\protocol\AvailableCommandsPacket#176998)
  #14 pmsrc/src/network/mcpe/handler/PreSpawnPacketHandler(126): pocketmine\network\mcpe\NetworkSession->syncAvailableCommands()
  #15 pmsrc/src/network/mcpe/NetworkSession(325): pocketmine\network\mcpe\handler\PreSpawnPacketHandler->setUp()
  #16 pmsrc/src/network/mcpe/NetworkSession(812): pocketmine\network\mcpe\NetworkSession->setHandler(object pocketmine\network\mcpe\handler\PreSpawnPacketHandler#177779)
  #17 pmsrc/src/network/mcpe/NetworkSession(276): pocketmine\network\mcpe\NetworkSession->beginSpawnSequence()
  #18 pmsrc/src/promise/Promise(45): pocketmine\network\mcpe\NetworkSession->onPlayerCreated(object pocketmine\player\Player#177844)
  #19 pmsrc/src/network/mcpe/NetworkSession(239): pocketmine\promise\Promise->onCompletion(object Closure#177845, object Closure#115148)
  #20 pmsrc/src/network/mcpe/NetworkSession(807): pocketmine\network\mcpe\NetworkSession->createPlayer()
  #21 pmsrc/src/network/mcpe/handler/ResourcePacksPacketHandler(142): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
  #22 pmsrc/vendor/pocketmine/bedrock-protocol/src/ResourcePackClientResponsePacket(61): pocketmine\network\mcpe\handler\ResourcePacksPacketHandler->handleResourcePackClientResponse(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#115907)
  #23 pmsrc/src/network/mcpe/NetworkSession(438): pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket->handle(object pocketmine\network\mcpe\handler\ResourcePacksPacketHandler#115167)
  #24 pmsrc/src/network/mcpe/NetworkSession(382): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#115907, string[4] ....)
  #25 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[7] c.`a`..)
  #26 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[16] ........&9...I..)
  #27 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#143309)
  #28 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #29 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
  #30 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #31 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1689218722.1994)
  #32 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
  #33 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #34 pmsrc/src/PocketMine(357): pocketmine\server()
  #35 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---
[03:25:22.197] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[03:25:22.200] [Server thread/EMERGENCY]: Please upload the "/home/container/crashdumps/Thu_Jul_13-03.25.22-UTC_2023.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[03:25:22.645] [Server thread/EMERGENCY]: The crash dump has been automatically submitted to the Crash Archive. You can view it on https://crash.pmmp.io/view/8953660 or use the ID #8953660.

**Comment by supercrafter333** [comment]
This error is caused by the virion `Commando`. It's not MultiWorlds fault.
