### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by SillierShark195** [CzechPMDevs/MultiWorld#296]
PocketMine-MP version: 5.3.0 [Protocol 594]
Git commit: d630b3af7bbdd5754dedd1ca4dd6e486fd3012ef
PHP version: 8.1.20
OS: Linux, linux

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: MultiWorld

Error: Call to a member function getParameters() on array
File: pmsrc/vendor/pocketmine/bedrock-protocol/src/AvailableCommandsPacket
Line: 533
Type: Error
Backtrace:
#0 pmsrc/vendor/pocketmine/bedrock-protocol/src/DataPacket(84): pocketmine\network\mcpe\protocol\AvailableCommandsPacket->encodePayload(object pocketmine\network\mcpe\protocol\serializer\PacketSerializer#132943)
#1 pmsrc/src/network/mcpe/NetworkSession(489): pocketmine\network\mcpe\protocol\DataPacket->encode(object pocketmine\network\mcpe\protocol\serializer\PacketSerializer#132943)
#2 pmsrc/src/network/mcpe/NetworkSession(470): pocketmine\network\mcpe\NetworkSession::encodePacketTimed(object pocketmine\network\mcpe\protocol\serializer\PacketSerializer#132943, object pocketmine\network\mcpe\protocol\AvailableCommandsPacket#132942)
#3 plugins/MultiWorld_v2.1.0-beta2/src/czechpmdevs/multiworld/libs/CortexPE/Commando/PacketHooker(81): pocketmine\network\mcpe\NetworkSession->sendDataPacket(object pocketmine\network\mcpe\protocol\AvailableCommandsPacket#132942)
#4 plugins/MultiWorld_v2.1.0-beta2/src/czechpmdevs/multiworld/libs/CortexPE/Commando/libs/muqsit/simplepackethandler/interceptor/PacketInterceptorListener(81): czechpmdevs\multiworld\libs\CortexPE\Commando\PacketHooker::czechpmdevs\multiworld\libs\CortexPE\Commando\{closure}(object pocketmine\network\mcpe\protocol\AvailableCommandsPacket#132942, object pocketmine\network\mcpe\NetworkSession#157711)
#5 pmsrc/src/event/RegisteredListener(61): czechpmdevs\multiworld\libs\CortexPE\Commando\libs\muqsit\simplepackethandler\interceptor\PacketInterceptorListener->czechpmdevs\multiworld\libs\CortexPE\Commando\libs\muqsit\simplepackethandler\interceptor\{closure}(object pocketmine\event\server\DataPacketSendEvent#179629)
#6 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketSendEvent#179629)
#7 pmsrc/src/network/mcpe/NetworkSession(463): pocketmine\event\Event->call()
#8 pmsrc/src/network/mcpe/NetworkSession(997): pocketmine\network\mcpe\NetworkSession->sendDataPacket(object pocketmine\network\mcpe\protocol\AvailableCommandsPacket#132942)
#9 pmsrc/src/network/mcpe/handler/PreSpawnPacketHandler(126): pocketmine\network\mcpe\NetworkSession->syncAvailableCommands()
#10 pmsrc/src/network/mcpe/NetworkSession(325): pocketmine\network\mcpe\handler\PreSpawnPacketHandler->setUp()
#11 pmsrc/src/network/mcpe/NetworkSession(812): pocketmine\network\mcpe\NetworkSession->setHandler(object pocketmine\network\mcpe\handler\PreSpawnPacketHandler#139437)
#12 pmsrc/src/network/mcpe/NetworkSession(276): pocketmine\network\mcpe\NetworkSession->beginSpawnSequence()
#13 pmsrc/src/promise/Promise(45): pocketmine\network\mcpe\NetworkSession->onPlayerCreated(object pocketmine\player\Player#139905)
#14 pmsrc/src/network/mcpe/NetworkSession(239): pocketmine\promise\Promise->onCompletion(object Closure#139997, object Closure#139977)
#15 pmsrc/src/network/mcpe/NetworkSession(807): pocketmine\network\mcpe\NetworkSession->createPlayer()
#16 pmsrc/src/network/mcpe/handler/ResourcePacksPacketHandler(142): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
#17 pmsrc/vendor/pocketmine/bedrock-protocol/src/ResourcePackClientResponsePacket(61): pocketmine\network\mcpe\handler\ResourcePacksPacketHandler->handleResourcePackClientResponse(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#140051)
#18 pmsrc/src/network/mcpe/NetworkSession(438): pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket->handle(object pocketmine\network\mcpe\handler\ResourcePacksPacketHandler#139958)
#19 pmsrc/src/network/mcpe/NetworkSession(382): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#140051, string[4] ....)
#20 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[7] c.`a`..)
#21 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[16] .O.=W4JK........)
#22 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#168237)
#23 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#24 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#25 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#26 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1689237547.1284)
#27 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
#28 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#29 pmsrc/src/PocketMine(357): pocketmine\server()
#30 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

Code:
[524] 		}
[525] 		foreach($this->softEnums as $enum){
[526] 			$addEnumFn($enum);
[527] 		}
[528] 		foreach($this->commandData as $commandData){
[529] 			if($commandData->aliases !== null){
[530] 				$addEnumFn($commandData->aliases);
[531] 			}
[532] 			foreach($commandData->overloads as $overload){
[533] 				foreach($overload->getParameters() as $parameter){
[534] 					if($parameter->enum !== null){
[535] 						$addEnumFn($parameter->enum);
[536] 					}
[537] 
[538] 					if($parameter->postfix !== null){
[539] 						$postfixIndexes[$parameter->postfix] = $postfixIndexes[$parameter->postfix] ?? count($postfixIndexes);
[540] 					}
[541] 				}
[542] 			}
[543] 			foreach($commandData->chainedSubCommandData as $chainedSubCommandData){

**Comment by VixikHD** [comment]
Invalid
