### ISSUE TITLE
Bug 2

### ISSUE THREAD

**Issue by SillierShark195** [CzechPMDevs/MultiWorld#297]
PocketMine-MP version: 5.3.0 [Protocol 594]
Git commit: d630b3af7bbdd5754dedd1ca4dd6e486fd3012ef
PHP version: 8.1.20
OS: Linux, linux

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: MultiWorld

Error: Tag "RandomSeed" does not exist
File: pmsrc/vendor/pocketmine/nbt/src/tag/CompoundTag
Line: 156
Type: pocketmine\nbt\NoSuchTagException
Backtrace:
#0 pmsrc/vendor/pocketmine/nbt/src/tag/CompoundTag(179): pocketmine\nbt\tag\CompoundTag->getTagValue(string[10] RandomSeed, string[26] pocketmine\nbt\tag\LongTag, null)
#1 pmsrc/src/world/format/io/data/BaseNbtWorldData(132): pocketmine\nbt\tag\CompoundTag->getLong(string[10] RandomSeed)
#2 pmsrc/src/world/format/io/FormatConverter(111): pocketmine\world\format\io\data\BaseNbtWorldData->getSeed()
#3 pmsrc/src/world/format/io/FormatConverter(72): pocketmine\world\format\io\FormatConverter->generateNew()
#4 pmsrc/src/world/WorldManager(243): pocketmine\world\format\io\FormatConverter->execute()
#5 plugins/MultiWorld_v2.1.0-beta2/src/czechpmdevs/multiworld/util/WorldUtils(167): pocketmine\world\WorldManager->loadWorld(string[6] Dragon, true)
#6 plugins/MultiWorld_v2.1.0-beta2/src/czechpmdevs/multiworld/util/WorldUtils(197): czechpmdevs\multiworld\util\WorldUtils::lazyLoadWorld(string[6] Dragon)
#7 plugins/MultiWorld_v2.1.0-beta2/src/czechpmdevs/multiworld/command/subcommand/TeleportSubCommand(51): czechpmdevs\multiworld\util\WorldUtils::getLoadedWorldByName(string[6] Dragon)
#8 plugins/MultiWorld_v2.1.0-beta2/src/czechpmdevs/multiworld/libs/CortexPE/Commando/BaseCommand(144): czechpmdevs\multiworld\command\subcommand\TeleportSubCommand->onRun(object pocketmine\player\Player#97479, string[2] mw, array[1])
#9 pmsrc/src/command/SimpleCommandMap(212): czechpmdevs\multiworld\libs\CortexPE\Commando\BaseCommand->execute(object pocketmine\player\Player#97479, string[2] mw, array[1])
#10 pmsrc/src/Server(1415): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#97479, string[12] mw tp Dragon)
#11 pmsrc/src/player/Player(1503): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#97479, string[12] mw tp Dragon)
#12 pmsrc/src/network/mcpe/handler/InGamePacketHandler(823): pocketmine\player\Player->chat(string[13] /mw tp Dragon)
#13 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#105962)
#14 pmsrc/src/network/mcpe/NetworkSession(438): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#74708)
#15 pmsrc/src/network/mcpe/NetworkSession(382): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#105962, string[35] M./mw tp Dragon..A....7wG..No+....F)
#16 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[39] S....-W()Pp)JL..c....a.u.r......_.g`p..)
#17 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[48] ...B.4i.......F.s#KF61.............e.h.4i..kI.8.)
#18 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#168165)
#19 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#20 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#21 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#22 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1689286244.6505)
#23 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
#24 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#25 pmsrc/src/PocketMine(357): pocketmine\server()
#26 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

Code:
[147] 		$tag = $this->getTag($name);
[148] 		if($tag instanceof $expectedClass){
[149] 			return $tag->getValue();
[150] 		}
[151] 		if($tag !== null){
[152] 			throw new UnexpectedTagTypeException("Expected a tag of type $expectedClass, got " . get_class($tag));
[153] 		}
[154] 
[155] 		if($default === null){
[156] 			throw new NoSuchTagException("Tag \"$name\" does not exist");
[157] 		}
[158] 
[159] 		return $default;
[160] 	}
[161] 
[162] 	/*
[163] 	 * The following methods are wrappers around getTagValue() with type safety.
[164] 	 */
[165] 
[166] 	public function getByte(string $name, ?int $default = null) : int{

**Comment by SillierShark195** [comment]
Java map

**Comment by VixikHD** [comment]
Already handled in latest dev version

**Comment by SillierShark195** [comment]
> Already handled in latest dev version

Still not working

**Comment by SillierShark195** [comment]
PocketMine-MP version: 5.3.0 [Protocol 594]
Git commit: d630b3af7bbdd5754dedd1ca4dd6e486fd3012ef
PHP version: 8.1.20
OS: Linux, linux

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: MultiWorld

Error: Tag "RandomSeed" does not exist
File: pmsrc/vendor/pocketmine/nbt/src/tag/CompoundTag
Line: 156
Type: pocketmine\nbt\NoSuchTagException
Backtrace:
#0 pmsrc/vendor/pocketmine/nbt/src/tag/CompoundTag(179): pocketmine\nbt\tag\CompoundTag->getTagValue(string[10] RandomSeed, string[26] pocketmine\nbt\tag\LongTag, null)
#1 pmsrc/src/world/format/io/data/BaseNbtWorldData(132): pocketmine\nbt\tag\CompoundTag->getLong(string[10] RandomSeed)
#2 pmsrc/src/world/format/io/FormatConverter(111): pocketmine\world\format\io\data\BaseNbtWorldData->getSeed()
#3 pmsrc/src/world/format/io/FormatConverter(72): pocketmine\world\format\io\FormatConverter->generateNew()
#4 pmsrc/src/world/WorldManager(243): pocketmine\world\format\io\FormatConverter->execute()
#5 plugins/MultiWorld_dev-281.phar/src/czechpmdevs/multiworld/command/subcommand/LoadSubCommand(58): pocketmine\world\WorldManager->loadWorld(string[6] Dragon, true)
#6 plugins/MultiWorld_dev-281.phar/src/czechpmdevs/multiworld/libs/CortexPE/Commando/BaseCommand(144): czechpmdevs\multiworld\command\subcommand\LoadSubCommand->onRun(object pocketmine\console\ConsoleCommandSender#41331, string[2] mw, array[1])
#7 pmsrc/src/command/SimpleCommandMap(212): czechpmdevs\multiworld\libs\CortexPE\Commando\BaseCommand->execute(object pocketmine\console\ConsoleCommandSender#41331, string[2] mw, array[1])
#8 pmsrc/src/Server(1415): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\console\ConsoleCommandSender#41331, string[14] mw load Dragon)
#9 pmsrc/src/Server(1831): pocketmine\Server->dispatchCommand(object pocketmine\console\ConsoleCommandSender#41331, string[14] mw load Dragon)
#10 pmsrc/src/Server(1671): pocketmine\Server->tick()
#11 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
#12 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#13 pmsrc/src/PocketMine(357): pocketmine\server()
#14 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

Code:
[147] 		$tag = $this->getTag($name);
[148] 		if($tag instanceof $expectedClass){
[149] 			return $tag->getValue();
[150] 		}
[151] 		if($tag !== null){
[152] 			throw new UnexpectedTagTypeException("Expected a tag of type $expectedClass, got " . get_class($tag));
[153] 		}
[154] 
[155] 		if($default === null){
[156] 			throw new NoSuchTagException("Tag \"$name\" does not exist");
[157] 		}
[158] 
[159] 		return $default;
[160] 	}
[161] 
[162] 	/*
[163] 	 * The following methods are wrappers around getTagValue() with type safety.
[164] 	 */
[165] 
[166] 	public function getByte(string $name, ?int $default = null) : int{



Dev-281
