### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xS91D** [CzechPMDevs/MultiWorld#300]
Thread: AsyncWorker#0
Error: czechpmdevs\multiworld\libs\muqsit\vanillagenerator\generator\ground\MesaGroundGenerator::setColoredGroundLayer(): Argument #5 ($color) must be of type pocketmine\block\utils\DyeColor, int given, called in /root/main/plugins/MultiWorld_PM5/src/czechpmdevs/multiworld/libs/muqsit/vanillagenerator/generator/ground/MesaGroundGenerator.php on line 121
File: plugins/MultiWorld_PM5/src/czechpmdevs/multiworld/libs/muqsit/vanillagenerator/generator/ground/MesaGroundGenerator
Line: 151
Type: TypeError

**Comment by VixikHD** [comment]
The issue does not match bug-report pattern. Since similar problem has already been fixed and you did not specify information from pattern such as plugin version, I am closing the issue.
