### ISSUE TITLE
Add /mw rename command

### ISSUE THREAD

**Issue by Hytlenz** [CzechPMDevs/MultiWorld#37]
- Issue Description: Suggestion, Add some command for renaming a world like automatically edits the level.dat for changing a world name and add some changing a gamemode for a world.
- Examples of Commands
* /mw name <old_world_name> <new_world_name> then automatically change in leve.dat
* /mw gm <creative:survival:adventure> then sets the world gamemode

- Version: 1.5.1

- Server Version: 3.5.0

**Comment by GamakCZ** [comment]
added
