### ISSUE TITLE
Crash on launch the server

### ISSUE THREAD

**Issue by dadodasyra** [CzechPMDevs/MultiWorld#38]
- Issue Description:
I changed the version of pocketmineMP and now that my server launches it crash, the crash dump is just below.

- Version:
SeeDevice 0.0.7 by Palente for API(s) 3.0.0
PiggyCustomEnchantsShop 1.2.1 by DaPigGuy for API(s) 3.2.0
EasyHomes 1.0.2 by JackMD for API(s) 3.0.0
WorldProtect 2.3.8 by aliuly for API(s) 3.0.0
GappleCooldown 2.0.1 by CaptainDuck for API(s) 3.0.0
CustomSetting 1.0.2 by LeNick for API(s) 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0
StaffChat 1.1.4 by Thunder33345 for API(s) 3.0.0
**MultiWorld 1.5.0 by CzechPMDevs, VixikCZ, fuyutsuki, kaliiks for API(s) 3.0.0**
BlockEffects 1.0.0 by killer549 for API(s) 3.0.0
SignEdit 1.4.1 by OtorisanVardo for API(s) 3.0.0
BuilderTools 1.1.0-beta2 by CzechPMDevs, VixikCZ for API(s) 3.0.0
Broadcaster 1.5 by EvolSoft for API(s) 3.0.0
BanItem 2.3.3 by LDX for API(s) 3.0.0
AnywhereBackpack 1.0.0 by korado531m7 for API(s) 3.3.1
BanWarn 1.2.3 by robske_110 for API(s) 3.0.0
AutoRestarter 1.0.0 by  for API(s) 3.0.0
Worlds 2.0.3 by survanetwork for API(s) 3.0.0
PureEntitiesX 0.6.0 by milk0417, RevivalPMMP for API(s) 3.0.0
WorldBorder 1.0.0-3.0.0 by ArceusMatt for API(s) 3.0.0
essentialsTP 1.2.1 by  for API(s) 3.0.0
LiveXYZ 0.7.0 by dktapps for API(s) 3.0.0
BlazinVanish 1.0.3 by iiFlamiinBlaze for API(s) 3.0.0
PlayerHead 1.0 by Enes5519 for API(s) 3.0.0-ALPHA12, 3.0.0
EconomyAPI 5.7.2 by onebone for API(s) 3.0.0
PurePerms 1.4.2-c2a by 64FF00 & ProjectInfinity for API(s) 3.0.0
VanillaEnchantments 4.0.0 by TheAz928 for API(s) 3.0.0, 3.1.0
LuckyBlock 0.0.2 by Palente for API(s) 3.2.3
BankNotes 2.0.1 by AndreasHGK for API(s) 3.0.0
Slapper 1.4.2 by jojoe77777 for API(s) 3.1.0
ScoreHud 2.0.0 by JackMD for API(s) 3.0.0
CombatLogger 0.0.6 by Jack Noordhuis for API(s) 3.0.0
InvSee 0.0.1 by BlockHorizons for API(s) 3.0.0
KitUI 1.3.1 by Infernus101 for API(s) 3.0.0
PiggyCustomEnchants 1.4.2 by DaPigGuy for API(s) 3.2.0
BuycraftPM 0.5.2 by Tebex Limited for API(s) 3.0.0
CustomShopUI 3.2.0 by TinyPixelDevz for API(s) 3.3.2
FactionsPro 1.3.12 by Tethered_ for API(s) 3.0.0
PureChat 1.4.11 by 64FF00 for API(s) 3.0.0
SimpleWarp 4.0.1 by Falkirks for API(s) 3.0.0

- Server Version:
PocketMine-MP version: 3.5.2

- Crashdump, backtrace or other files:
===BEGIN CRASH DUMP===
eNrtPP1T4ziW/4ouTN3CVBzifADJFFPHAD3du9Cda+jtud1sdSm2kmiwLY9lA+mp+d/vvSfZlg00
NM1t3Q/D1mzHz9LT+/6QZf/eWaos5vmna5FpqZLO1O92chkL+DEe7fdHgz3/oNuJuM5Ps0xlnenv
nXyTwu3OJfxjYN1OLLTmK4QeZasiFknOfJZyrUXIcsXiIsrljcqicD7nqZzPP+Lvn3ks3heR0Eez
N9NpkYY8F2fiWkTlje0dmKlzthCMJ0wmOudJIJhaslQFVyKPZSLm8winzOc0s8uSIorYSl6LpMsC
HkVAgExYuubZdHd3d61isRuoJOcwNdtNo2IFaHfPkT6iqYcjd3UW7NY0w4Q45km4q4tF+RNJzIDE
iwoEM1OmEhYBZjYZg1CWQMorGaFUvm19ENnuHYnheriIWeA5GGA2EtuZTgag84wH8POfna0+ewlx
bE/GO9NnK/7th7Mz1mU6z2SyYul12mULpSIBZrADZG/5T6WxHnZs6fL9QYswO3Y+rxmaz+9y5P0o
bkVQ5Ajadg2wmnOsEg1E2pUuRBKKjKnFryLIu4xnGd+wI/z/7Z2KtZVdhrgaMOSiRl1xcSHjtMJ7
ztPtwXjvISbucFzR/QyiLZXxTYt+InfYJvdCZBBGtv3JXh+ou3e1Nifej6HUKc+D9bdQV4kRTYUt
eaQFI7kQnaOH6IQA16LT3KmJKo3m/4y2MYNIFarMJU8nSn0WZNEXkRCpyF4D/ggpHvQfINiF/R5E
SheZ+GObltj7qiUOBq0VzFBYqTEOVsxUAFH/rcrlUgY8h+ShzYL7D8h7MNg/eCJyjdcfklxG26Eq
FiC8Ohv1Bnv9A1ro4KGF/OHkATnlMriaGcpVZsidPGQe+/74ASyQiLLczPb77ekz+nkOP7cHo4fo
+PQJsgDYSBHk2z9xLY4hw+ozxV0TcucVIAoNzg1540ytVncNrZ1aHrxR5hxDvX/nfk2+dz6j2Lrt
AxOZ+K2QmdguQ/L9Ce3u5N0HpYMJbKfzrz+6HfFnZfGVlcWLJH2QvCGzgQoGBCoUqI6DIdxh8PcH
AA9GcIH/ji1w9/vv8XLPXrLv2X+lPOMxI3mx70h6OGL/zghrRN+tLGE46uDOKMz47LtrHhU0YFIN
gKtJ3xmeibzIEhqPt/zq1i5eDuxlCnFEBrA2xKqALYskwJjF7rMOl4PuHWq7LmXgGnT1Oy5Vygv/
zGyINdcSnfrQArwfVyIvods7P+C0kTNNLrf/ozW1NE+wTgwVZ+7NHbPw2MGAf1YilG1oiT1nAGpz
sm+0OTlwSQaDS1WRhBW15TJENS18wnO+vUPXx3b0JV9tzzuVkc07hqvJfZghdor8ggS67QhUi2g5
na7KW68yFf8dpbtthUwY/X7fEO33/QcFDQvwa+GQamYOnAlmsUxEEG4rqrcNGhj+x5/F8J/F8J/F
8J/F8J/F8J/F8L+5GO52VgKm8gjLr4TjNlyngQboXICE6u26zrA37g0QXEgo3qb+/nDQ7Uj9KRTX
nSl5GJR5mcpVANXRdOgPYQ2Zw8Rl0N8/GITL/sA/WPLRYgKmtNcXfSEGi+H+0ud+EEx8sQDcGb+K
5ALm9Hv+oNcHSGGJO5NJccv2B5PhQoihNxzxpTcaT0KPh8ORNxmL0X54IEJ/NGKjnj/u9b3BxCMe
oQbbGvreh0WR5AW7OJ+xy0KwvxYR8/fBwKfDyXQ8YB8uj9mg7x+w24O9T3sjWBm3vaad/d6g5w/h
8jO4M0nB0AV3PyldEgYAuojooqp3NUr3QogTcS0D4Yi6hnU7tYT7vX5vHyC8yNcq01gXzHgEnYhA
hUEmR8gQBvXxWiQcXBRoAnsG0YfgykmIk+CeVsv8xAXEnKrval30iZoELFDQAN5dXH589/7sBEA3
YqFljrSu8zzVYHWgzHWx6EEg3i2pAkZncrXaHEOLo+LTJFjzJNcXa5W6ZvXACJdzH6Xc5PyEw8Sf
i02D9cHzWS/xzecPEGT8/DFpIM+nXG9egwtqh8sa1uSrTz7j8PVXHlydn7yUQg22+bxa/ulcULUC
UTmHgOYw0gC7vAx6w95BkxceySLavBQvBtt8Tnk6NRS02bm4PHp/+WH2mIGeQ9RcSgElaR0EvTIG
55kQuzHXOYTOBrcglJ95SpWSikJ1kzhiad1oCqbfNt5jnmJsPimCq5eSTmBQhoAS62SXmvb1U7Rv
7P9C5DkkFofPJvwRWz4Tb+VdDr2js9nrIzQV53LSvPT7rWu/dT0or58rrwYjT/eKi5wvl8dr7rpE
DWvKw++NmvK4XBdYjg6Hw9H4pfTu4oSoXZLi/HxGALdIT5TQM+sVNTqQgrNLU4uhsXXjymFMGdE1
/88iWM/OIb9gOPy7vJVXx/+gB1WbItfFlYTfV+Du8kq/lJjcrqxB6NeKxqHd6WNRKD9FEEtOl0sI
FW7kb4DbDtMSzJWMoNIejyZfZNsWU0/iu8I4ny+QEGEImc9bZD1u+HKVnIayYfclqMnVqB3t3uUq
k5onf+dZqF6sVLGLP911f8LCVGSXEAUb+nHBbQfuewuR88FTzPel4jgiT2OomkFJC0NbjrSBypqU
fovlNlChbDJAFlDOc0XjQFsu3ZTI6bWKLoChlxKCszCw3aDiCYn+5uamJ4AixN7Lr4g/nrzJRezy
ZiHtEmbYSmEnv7wUU4AKmDHLPs1q71EiIPHOj2enuyX9wNxRsrlZi0z8BMVeCv85XN659VgAUhkP
1Xjox/sNtofg089k20E5n7fpuQt5kifz5CPPkqY2CdJuGlrazNRCX4lPvt9/KaXWGEm3SMSzdWtw
Aardkh1UbpGr94L2Nhq+2YR/Wa0vlUxiCU44nwNilZVLgwZblDyts9DtnkLfKZpbytNFds0TkUMW
f7GqmXDalkLbjfDnxFaXtl2LBbvfIhOnSS5zKfQvbs/bgDd7/L22T8YyuuqPfOz830NHfs2j2fn5
7MUM2KBM4xg63BToEpYuaIQdKr+6xXJI3W2yW1rATyoLGybtQu8YtDe8G62OskAU+pznL5Z4HBKe
7cacqIqRKnymrDVKFLzscubw2gB/eavjhVhzV5zPW+s/6rNn8lr88j//cDgoIU3r3W/rKLzKofl8
sTrerjqf18s/ni4i/llC9ZlIvW4U5g64bW+t2CPlq4jHUiY46cW225pYsSavKWpePYXNWcQ3Inst
uNuUOcAWi60KLhF6PPYn9zfr395ul/ghqlQUub+ftK8WqETFGzw84Gys1UCXwTFYYqtsV4lYwH8v
pTyLDlzJUEBPUhvUPK4xiIszkcW6lRoMrN1VDbxgwJss7Y1ever32X+yWabwwcObZCkTmb/Yltsn
s4BJBUSV8/M5G8M4124o1HhAEmjlUcTtfiuernFlct9dVzqju6nhci2OPk8GB3ckgXbsP18i14YU
fM6YiWftrBi6du/jCeNsEVxtqDd3Q20NbD8PGDz+PACr4K/i1vWpmnOLGiJvRc2zU6TzgABK3au3
Km9sltewR/ZRj5IwE1y//vlvX2XxLQYf0nWNnWp7Q5Lz80nbJhFkv0aVU0LuuHeTtV/Vr0rs41+D
tW8wXW0WfrbSaop2Sx6QwQAc4XXh5pwK1NZe/9/xqKNc/ekbQ8cqXvDcPMF1t7pdcNvv9u6ywt4q
KBzXhXyxYudXwJqUSOmMAxAUEUEYgBrkPcrlm+T6QrgPGS2gzVnLxcjRX6tMflbJizHWQDqfG0og
stCj9qcw8zeZf3CrAHPddKlhmxXIjiJLCo3Htl6IEQflfE5EPN3s7nnO+OXHoo+FjH/rI9Gv2Xfd
BBlf5rPzxq5rBWwa4LjN1aVYiFt2JmPAGL6YAdrlgbXqVANusFqizGnUpz8mW6u0YY4NsMtfeTzA
5U8mm5m8FdGJuP7c2nQbvEgai8TtjOP2hiEI/uVRXq9p4I9xq3FOinN6K46sv+J0blVD6elw7kLv
uOMdzea48xd++jatUslsH3QdQU97kfIYl68l4BA1n9uLJ3tpibxZot/zuG/U8/37yvOvK03qsvgu
o03h/iKupSr07NQr4Z0HKnfzQNAh+1vr9vI5oDk4+JFnaeOxUAVsF+kt+bzi0ZXMvvUhH6DR+WXG
E72k5HERqRvn8rTa6ZidOgJa2rXnc0303gC95UlIS/sjtoHHePB8uMiFYad3z0kr0iIdL+ulmYKa
iTbTpp2tWXXFjhW0bSuGh+nn2TzZulwX7K88YUPm700Hw6nfL48fTfB+rPLwcF70+3zfP4pUEUkV
C2YAg22RsBB/i8n1Do42i3upyvJDvz8ajxB4swYmvEhqgOE1TxJVJAGegcCG3OPBWoprQV3JoVou
CVHKbxLPnrsAlR76e0QNv7Wz9OG4Xw+E9iYGmR+qpIbFalGhwwOYsQrFIc1ZqgxWr2B2DMgvxGqu
vE6vU4svlMulDAoISYdDwkan1XKVedo80deHCDYn3dEuD82z3wqmhQidIfjCx+HJ6aujD2eXCDXW
5/1WiGxziBboADOIuiVF+LuHb4EA+vDwe/oDcRa58vD4t6X2WoobL5Tm9PzhAYJuF+rWQ1ewQyKe
rAq+EofLTDhqk+kh1mTwPwQSOb2mKvGsWXWGpbeJIzQuhtGNBWRXRUbHQMm8GMiZNYwUzI1BT6oF
KwXHeCYYBGamErDNHDydBWgf9JKKTIKoCM0bJ3fMGnFdoC2qJSJo49R8KbpMYczXiJItoLu6YhtV
ZBYXk0sG+pdLSSuA6jOwtWiDiN+KmwrdbiiWHJSv2Y1K/pIzbEZ4xlDsMb5UwaNogxTma6kN3zdr
gW9YrDIeAoLePEEJG2TTecK2Pq4pF+GbPBAtQgYY7FFNEAHGkojn5kUfSykUsNDDMhBnJHISV0in
5diaTssiJAbExq5L5U7NSWOA63WR41Ecz75WNGXzDp1CBVlA2IqNBzO8KRE1ywUDWah5B6k9iiDE
MXRfOvVpAjO7lpz9N1oIDCFLKU80TRlZMEyERH/DOBoGnpFmdnEjHW4RsUKD3iHewnrENJQXMBKC
NpQQiXPDAzkslBY1+lNykBIPCIKh9zKwEFACkrrYMKs6GG7dqbpbS2frowT5qwS0yMMQGNdG2Ugm
nhUGcjiepaa3sEDFC4HyAF2I3woeoZbo9ShG72ywbbskBNAdQG7WAzcW6EgeKBk7qCncxZXfFvEC
z/Eu2ZHeJMEl11d4MPwKbLaH9z/g+17oRSWTOGqdQR1WgKXAaN01B8mZDUngel2Gb50AF5gJSSyQ
RhAWF4k9pE24L8iSgB+w50zdQvzMBYgA2CEfSSrSUKqGnDdLdAocgsbfZTL/C0guz2hWKDBUk3G2
5rJt4AD0zAYoEeLBs1xOCVPLJzgZXFYkCWoxxJCpUpI+nVDQPQaFpP3NYrlaQ8zIuF53XR+31ojS
yLIizQ3UCAuFEgNlhilSKpp7HOP5ffI7fq1kCDTfTwCjZ8gsVSBjMKpebV4w1jNjKvuCpAVpJtuQ
5/8cqQXYDJYUzIDBsaDXwPgRixVfbHKQNbswUu6TXKVG1Dj7EtV1I0nmZEcQGG48g6c0LU3cLWVG
7/gB6QmhgkAvyhWNZYOeCvLHlQIVKQwzaA6wzoqI9IiwKesjC2yLYny+BgGH/8/Jx5LrC8Rjmv8m
4qHZSml9G5wreiw2zSBamHc1S2pwzZIkvz8YGarI5z+SI1ji9F++nTxyBaIHAwQLCkhrCaQ1Zl4B
QotWhl7jg5gGq9HiNoBSRdfsUJR6d3k6ZZev31ywszfnby4hRs/O3pxesNnpewa16t9O33cZDGKX
72DUKfv4+t3ZKZu9f3d8enHRa7l8QxaD8Z4RBfQgUlGex4irkblgLSj2kiSqqOqD1CGhhBhJaIQH
UU+YeIqIoLoFFiEOgwkhqw9ZmLEsqEwxrSY4zC41p0oGcUCMreO1STq4wjtMFFg60PDe3cFoAbaf
AHWlIsAKw4gUaTX6NHMrBsCoRKprNod9y6feuZcgy/XQcL3i2QJcwQtUFJlyGYPNvVIlz0JS7Bxm
50CEjnlSUC3jUgF1XgF2h2+r3Wt41vJM9jTn+wh9XHtcj70zkd2YOFQj0EWEFSUSEsVNwmra0YdZ
SqQDh3v9vmGSbb2iqHAnBZKxmNkVV8tMxWUmxbn2vudaoqNU4MLqrm0L9xiQawwXZcmJKspgEXrh
y9hsWMSpKdBMEWjhHsKNfk5whB1NFBN5Jd1wBakbPJrfI1JIxZDQAP01GJTWhUDvz9egpVVZrGJY
wrVqkrql4kzitzUpkkYDH5IONl3BukiutCH7mKcIk3ERQ96kV97KdgP1xkyDZgiohYluYSVIjnHX
nKBMT4kYWszD6rmAPLpnVXSizI226WKZgxHN4MahpZMYPHaYwxBVAV4AfaewLJ0ABVR1QAWI8gKi
TKlgUOBRMYGdCc4wjNVMwTSSoGGiXBSHVrUqyCzCnsHi/BKaL9nbPLGHfqYm5ENttVaRqRAX+K4i
FehEKxQ+YC02Z1DIMj2SvWtSxUJUtSLlqi1XKeUdDJXZJkfcXeb5jr5QV7Ssl5ek2JCOcbiuQanp
xQIwNDxjz0P1Oc4FoKWpx15DLUcvjWNxxo5nH7owFyhYgBPdyBDMm1I+RcQKvUfop2zfFsx1Ka1J
MM7QHjsKIQCtebTchX7TVPehAHO1C8GSDPdh0J4cd6tSmIPL6R9ObzFaYX3Io64JhbjwR5lA0wVs
QWwRFKWwBv4wS2ZlBV23j9gc4KQbSI5z7B2T1LOXzV7l3Pqdlp9FpWH6goNVLG4/leUQVOLGXpz8
OZoMzKSdHpvZORHPVjSB2y7WWgcuuMz4ClkDPQFPOo2oIsHWNMavQYC38wx1dxxJ3L+hVhtfFBQ6
Z+eXH4hQDQwhz4siZ9jak3rr1Uy70LORJs4LDydNiVY0+lAsipUxeWUzK8PyKiPXt2UNNj6YovDN
uF51V6OMTD+wTnsykUiGT/osR5gAgAcgMas7M3EXweZx88kLQgAxFKoLVGA9MubgwTFoIEfDgcYF
PyWGoZC+MoZhETCXJQEuB3pNPLn0LKzuaSGs/8h87KxsrYktNPFfts/abDWIsq2eW/+aElu2KdZs
Fz/4UEAU2F0Fxl/wBWW3KzFRmsR6vFZKU2NetmCi7K0pkoc850zza5sscK+p3LvDWxX5HBiH+Cd4
boQK3JgDn2XVT40ieBAVXzqFUpOKsUQFkUwZzQRTOgdxBhydJVbXZduNKY5kR3HaK++Y5XQdI8sN
N2e75ZL2S4z9m+++mY0mGmqNvdB2YyIAh88pGtopnpkyZSlI8FpGVLk3nBcfUUE6sugoqFBNhx9q
gSCCL0pBfWprMEyQprRDgeHWHcJtPVfKsQGuiuW+DdGmHMAXYp3Ftn2Im/es0mUDuOHfd0PkQW+H
YrgWLhVkSJeIGTem7HYrE5C1zHqoPiMs2l6r993CMouiW1PhH93wjTa4LR7HAk2mtNmg9G8rTNtb
JSj7qF1ldMtRja3Oe3cJqcU/ilWBUXFp0rkNkmiKljeUChKJGzZg1PhzykY49T0VIc5UspxEmG2C
hTCoFmKJIY32nal8WJe+g+5Cu9FlNTOqOcdlSs4hrjPeJtO+Xw9rVcJvUti/l0Se0ddMeOm+QKid
apVsKBli6MDdE898fqNWDQuwWjFqw30/Jz6d0EL0co+mWI5SNIEO7BASXswsW8zsM5VlEU1xWWZb
HpjmFltBv6prodQbWaVcencFY0PgDZfUz0K2MTF5gZsyaRFZD7a/sUigITavHOBq5A5eaiIgOhxG
NSg2bbtBLmg27abG7XB/kVprAzXFhdUQvtRX7gHV0Rwt28OvCjUhVWxqQCG9yGSpah1ARPLMw7Fy
3FqhKoiIHp6g7klFpCYq2cTYHNJHfjRwpiuasdu1t1l9m2inqM5Xq0ys7MZhtSWL1TV+DeaqxZj5
dMXW5buTd/g5AJu/bM2AAeFGmJaEg4vc0IKayK6oJ1DPeYYAFUolb2OHpJG2LEGF5u60yp82AdZF
NkGVIzDoVBK0CWcHrwsxKV3zLsM3raiiyctSFvLSUmTQnHgYXRJMqeamTcxmN5A39gPtA0cnYRdQ
skPpQwGqDAUWH6ra3C5XaOvWsOgqFyqJKo/ZNI0YcXhZUaIuMRDialTq2DnlTnavQm9vuPhLIX6x
DLDB2KjTmL+zjVTu7+cyN4IsN4zWFkYRARtC23PYkIBb7dDKhVR5y2WFB/o14MLUXxhhnMKJ0Nng
VyZ8HknIX0ZCp7ccn6iaC6ydgD6rommpK7oFNorbeFP2TypmIGt1aV/vX4jRvJ9Rlg7ugyXiAIvr
TIZ2G6V8FEjF530ZiCocSouaegtqx/FVTiDU1gwO6bQqEUC/GD45xEBPyahebcpenR1dTgc/7HfH
k1u/O7wddgc/+D+EkNpN9NzGF8sDjJuHB30TZM3VaLxjyj/ztMbZxTB+jNkCRGs3E6kMo91A0FWw
YeZ7JUVWhtuyq8uqBzEUVgAPJJ+AKmddysorHxGBBVC5v/XKfApHmjIjaOKgl4It5JMD8ajo7FW7
niq1fQDENm174eAKWydNzR+IYyGhbdmYHRIah9zSB8Yikx/ISQyLhB2KisyGu063I25zkWg68zD9
vUNncZ1vcaDLuteg+ETryAWlQXOK/g3oEcPGFz3Mp0aq60UABebaheAjwCTkWQOWbdJc0VEmcwAt
sB8TrEcUWYOUX7U9QGLe/FnKiN70qgcs88aXRlZh4ypu3FxzfMfBnu/HKgzIa4y/mJ25l2Tuofmk
innxJF6YB5/uqHgD8qHvm9hfbIynOQb4dIV5eDJh3B/19+Hnd29wi/BgKfhgtBwcjPaXfH/sT/p9
fyGGk34wOeCizwO+FMODffYdaSLJG/KYrUmiA3u6uc5Mn6jWoI/umE/AmC+tKC1vG6q125p03Mrv
7eMHaPDVqaXdmmqofR2rhvw0raYb1qTtazl45lOuFjLh2cYSiF8xyNWVSKCMaehsw+lJPI7BjwB8
lql5o3hMlyRFWY//44//BckE6z4=
===END CRASH DUMP===

**Comment by GamakCZ** [comment]
Upload crash to https://crash.pmmp.io

**Comment by GamakCZ** [comment]
Closed due to innactivity
