### ISSUE TITLE
It doesn't generate worlds when world name folder already exists

### ISSUE THREAD

**Issue by Saxavlax001** [CzechPMDevs/MultiWorld#41]
- Issue Description:I type in console "mw create BridgeEW 1 void" for example and it can't load the world because there isn't a level.dat file

- Version:I tested 1.5.0 from poggit and 1.5.1beta1 from github.

- Server Version:pocketmine 3.6.2 release(1.9.0)

- Crashdump, backtrace or other files:No crash

**Comment by GamakCZ** [comment]
fixed
