### ISSUE TITLE
Empty command response

### ISSUE THREAD

**Issue by dearminder** [CzechPMDevs/MultiWorld#43]
- Issue Description: Every time I type command /mw (anything) it responds empty lines

- Version: dev-131

- Server Version:3.6.2

- Crashdump, backtrace or other files:
> mw
[07:29:20] [Server thread/INFO]: 
> mw help
[07:29:25] [Server thread/INFO]:

**Comment by GamakCZ** [comment]
response of command 'pl' ?

**Comment by dearminder** [comment]
?  Of command /mw or anything related with this plugin. Older version works fine

**Comment by GamakCZ** [comment]
what language are you using in minecraft?

**Comment by GamakCZ** [comment]
unconfirmed
