### ISSUE TITLE
Server Crash when running /mw gamerule

### ISSUE THREAD

**Issue by 100PXSquared** [CzechPMDevs/MultiWorld#47]
- Issue Description: When attempting to run the `/mw gamerule` command the server crashes

- Version: 1.5.0

- Server Version: 1.10.0

- Crashdump, backtrace or other files:
[Fri_Apr_12-15.37.14-GMT_2019.log](https://github.com/CzechPMDevs/MultiWorld/files/3074079/Fri_Apr_12-15.37.14-GMT_2019.log)

**Comment by 100PXSquared** [comment]
I think I figured out the problem: when running the command from in game it works, but running it from the console doesn't work. Turns out the command needs to be passed a world but the field world isn't required for the command to run, meaning it works in-game where it detects the world the player is in, but not from the server console.

To fix this issue I suggest checking if the world passed or the world detected is null and if so exiting the command with a message like: `World not specified`

**Comment by GamakCZ** [comment]
thx for reporting :+1:

**Comment by GamakCZ** [comment]
fixed
