### ISSUE TITLE
Add Support for PHP 7.3 

### ISSUE THREAD

**Issue by SchdowNVIDIA** [CzechPMDevs/MultiWorld#51]
- Issue Description: MultiWorld isn't working for Pocketmine when using PHP 7.3

- Version: 1.5.0

- Server Version: PMMP 3.8.2

- Crashdump, backtrace or other files:
PocketMine-MP Crash Dump Sat May 18 19:24:31 CEST 2019

Error: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?
File: plugins/MultiWorld (1).phar/src/multiworld/api/WorldGameRulesAPI
Line: 182
Type: ErrorException

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: MultiWorld v1.5.0

Code:
[173]      * @param Level $level
[174]      * @param array $gameRules
[175]      */
[176]     public static function handleGameRuleChange(Level $level, array $gameRules) {
[177]         foreach ($gameRules as $gameRule => [$valueType, $value]) {
[178]             switch ($gameRule) {
[179]                 case "doDaylightCycle":
[180]                     $level->setTime(0);
[181]                     $level->stopTime = !$value;
[182]                     continue;
[183]             }
[184]         }
[185]     }
[186] 
[187]     /**
[188]      * @param bool|int|string $value
[189]      *
[190]      * @return string
[191]      */
[192]     private static function getStringFromValue($value): string {

Backtrace:
#0 vendor/pocketmine/spl/BaseClassLoader(126): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?, string phar:///servers/citybuild-test2/plugins/MultiWorld (1).phar/src/multiworld/api/WorldGameRulesAPI.php, integer 182, array Array())
#1 vendor/pocketmine/spl/BaseClassLoader(126): include()
#2 (): BaseClassLoader->loadClass(string multiworld\api\WorldGameRulesAPI)
#3 plugins/MultiWorld (1).phar/src/multiworld/EventListener(85): spl_autoload_call(string multiworld\api\WorldGameRulesAPI)
#4 src/pocketmine/plugin/MethodEventExecutor(38): multiworld\EventListener->onLevelLoad(pocketmine\event\level\LevelLoadEvent object)
#5 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(multiworld\EventListener object, pocketmine\event\level\LevelLoadEvent object)
#6 src/pocketmine/event/Event(99): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\level\LevelLoadEvent object)
#7 src/pocketmine/Server(1110): pocketmine\event\Event->call()
#8 plugins/Texter (1).phar/src/tokyo/pmmp/Texter/task/PrepareTextsTask(103): pocketmine\Server->loadLevel(string Plots)
#9 src/pocketmine/scheduler/TaskHandler(159): tokyo\pmmp\Texter\task\PrepareTextsTask->onRun(integer 23)
#10 src/pocketmine/scheduler/TaskScheduler(199): pocketmine\scheduler\TaskHandler->run(integer 23)
#11 src/pocketmine/plugin/PluginManager(688): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 23)
#12 src/pocketmine/Server(2558): pocketmine\plugin\PluginManager->tickSchedulers(integer 23)
#13 src/pocketmine/Server(2334): pocketmine\Server->tick()
#14 src/pocketmine/Server(2195): pocketmine\Server->tickProcessor()
#15 src/pocketmine/Server(1774): pocketmine\Server->start()
#16 src/pocketmine/PocketMine(266): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /servers/citybuild-test2/, string /servers/citybuild-test2/plugins/)
#17 (1): require(string phar:///servers/citybuild-test2/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by GamakCZ** [comment]
fixed
