### ISSUE TITLE
Better normal generator

### ISSUE THREAD

**Issue by ghost** [CzechPMDevs/MultiWorld#53]
- more biomes
- more villages
- better caves
- and more....

**Comment by nickalyn** [comment]
Agreed ^

**Comment by Wertzui123** [comment]
Would be cool 😄

**Comment by SchdowNVIDIA** [comment]
Doing this with a plugin mostly ends badly. Just look at BetterGen. After using it a week the entire world laggs as hell.

**Comment by GamakCZ** [comment]
Thats caused by slow server

**Comment by SchdowNVIDIA** [comment]
Intel Xeon E5-2687W v2 3,40Ghz (4Ghz Turbo)
16GB Ram
60GB SSD
Isn't slow.

**Comment by Wertzui123** [comment]
Hm.

**Comment by SchdowNVIDIA** [comment]
Well if you do real chunk generation it would work. BetterGen was done with (overusing) setBlock

**Comment by fuyutsuki** [comment]
What we needs to does with this plugin is _**world management**_. There is no need to do anything more.
So how about preferentially using that generator only if you have a [BetterGen plugin](https://github.com/poggit-orphanage/BetterGen)?

**Comment by GamakCZ** [comment]
BetterGen is buggy and outdated. It uses slow methods (lots of populators) for slow software. Also I think world management methods are too good enough for managing.

**Comment by MistakingManx** [comment]
The normal generator and seed keeps using the default pocketmine stuff, it's so bothersome and I'd love for better normal generators to be here <3
