### ISSUE TITLE
Undefined index: en_US

### ISSUE THREAD

**Issue by ver24436** [CzechPMDevs/MultiWorld#59]
- Issue Description:

Installed latest release of PMMP and MultiWorld - Server loads fine, but anytime I try to execute /mw   command I get the following error.

`[Server thread/ERROR]: [MultiWorld] LanguageManager error: Undefined index: en_US Try remove language resources and restart the server.`

Seems the issue started as far back as "MultiWorld_dev-114"

- Version:1.5.1

- Server Version: 3.8.4  BE v1.11.0 (protocol version 354)

**Comment by GamakCZ** [comment]
english language pack is still full however if you want to remove this bug, you can change your MCPE language to english or fix your language fill with pull request

**Comment by ver24436** [comment]
Sorry - I don't quite understand.  My language is set to English on both MCPE and PMMP server settings.

![image](https://user-images.githubusercontent.com/35013625/59898754-09845600-93a7-11e9-8d4c-daeeed152fec.png)

If I run MultiWorld_dev-113 - this error does not happen.

**Comment by w1455278080** [comment]
I have the same problem, and I haven’t fixed it for a long time. I hope the author can fix it.

**Comment by ver24436** [comment]
> I have the same problem, and I haven’t fixed it for a long time. I hope the author can fix it.

Does anyone know the fix? Seems issue is now closed - and being ignored.  It started being an issue since MultiWorld_dev-114
