### ISSUE TITLE
MultiWorld does not support Apollo

### ISSUE THREAD

**Issue by David-AI** [CzechPMDevs/MultiWorld#6]
- Issue Description: Server thread/CRITICAL MultiWorld does not support Apollo

Make it support Apollo

- Version: 1.3.0

- Server Version: 3.0.0 API server

- Crashdump, backtrace or other files:

**Comment by GamakCZ** [comment]
What is apolo? :D

**Comment by David-AI** [comment]
Apollo is a server phar. https://github.com/Apollo-SoftwareTeam/Apollo-Legacy

**Comment by GamakCZ** [comment]
Apollo does not support multiwold :/
