### ISSUE TITLE
I Can't Give Permission mw.cmd.teleport To A User

### ISSUE THREAD

**Issue by WHOAMI74** [CzechPMDevs/MultiWorld#60]
- Issue Description:
Can't Give Permission mw.cmd.teleport

- Version:1.5.1

- Server Version:3.8.4

- Crashdump, backtrace or other files: None

I already add permission mw.cmd.teleport to a group with pureperms ,but the users who are in the group that I have given the permissions still cannot use /mw teleport

**Comment by GamakCZ** [comment]
It should be fixed in next release
