### ISSUE TITLE
I have a Minecraft server at minehub and I have the plugin on it, but whenever I want to go into another mw world my server crashes and it says "Server closed". Please help

### ISSUE THREAD

**Issue by 34561** [CzechPMDevs/MultiWorld#62]
- Issue Description:

- Version: MultiWorld_v1.5?0-beta2.phar

- Server Version: McPe v: 1.12.0

- Crashdump, backtrace or other files:

**Comment by Baducai** [comment]
Please speak english

Die verstehen nur Englisch.

**Comment by GamakCZ** [comment]
If the server crashes, send me crashdump

**Comment by GamakCZ** [comment]
probably fixed
