### ISSUE TITLE
undefined index: en_US

### ISSUE THREAD

**Issue by mote166** [CzechPMDevs/MultiWorld#63]
- Issue Description: whenever i try any command i get this error

- Version: 1.5.1

- Server Version: Pocketmine-MP 3.9.1

- Crashdump, backtrace or other files:

 LanguageManager error: Undefined index: en_US Try remove language resources and restart the server.

**Comment by GamakCZ** [comment]
remove `/plugin_data/MultiWorld/languages` folder and this error disapear

**Comment by mote166** [comment]
no the error is still there

**Comment by GamakCZ** [comment]
have you restarted the server?

**Comment by mote166** [comment]
yes i did but still nothing fixed, sorry for the late reply.

**Comment by GamakCZ** [comment]
In what command this error occours?

**Comment by mote166** [comment]
it occurs with any command which will make the plugin send a message or say something, like /mw , /mw tp , /mw help. 

the plugin works fine but no messages ingame and this error on console, its just annoying.

**Comment by mote166** [comment]
i just tried to change the language in config.yml to something else but the same error is shown, Undefined index: en_US

**Comment by GamakCZ** [comment]
What language have you set in minecraft?

**Comment by mote166** [comment]
english in everything

**Comment by mote166** [comment]
this issue is solved, it appears to only happen when the server is made by pocketmine-MP (android) , when i moved all the plugins and data to a web hosting site the issue no longer occurs.
