### ISSUE TITLE
Setting gamerules from the server console is not working

### ISSUE THREAD

**Issue by Shaggy0815** [CzechPMDevs/MultiWorld#67]
**From the server itself if you try to run as per help command:**
[Server thread/INFO]: Usage: /mw gamerule <list|gamerule> [true|false] [level]
**On this server pvp is a world name.**

mw gamerule doDaylightCycle true pvp
[15:42:15] [Server thread/INFO]: [MultiWorld] World true not found.
**It recognizes the parameter [true|false] as the world name.**

**changing order does not help**

mw gamerule doDaylightCycle pvp true
[16:09:03] [Server thread/INFO]: Usage: /mw gamerule <list|gamerule> [true|false] [level]
mw gamerule doDaylightCycle pvp 
[16:09:17] [Server thread/INFO]: Usage: /mw gamerule <list|gamerule> [true|false] [level]

**Running it on connected through a client is working.**
**I assume this is either an issue of the command line not passing a parameter or it should give back**
[15:45:13] [Server thread/INFO]: This command can be used only in-game!

**Like it does for other commands.
Or is there anything I am missing here :)**

- Version:MultiWorld v1.5.1

- Server Version:PocketMine-MP 3.9.2

**Comment by Kjenium** [comment]
same problem on the client for me

**Comment by GamakCZ** [comment]
You haven't specified level arg

**Comment by GamakCZ** [comment]
Try 'mw gamerule pvp false world'
