### ISSUE TITLE
Changing dimensions stucks

### ISSUE THREAD

**Issue by HimmelKreis4865** [CzechPMDevs/MultiWorld#69]
Hello,
I created a Nether and an End level using the MultiWorld generators. But, when I try to teleport to these levels I always get the loading screen as long as I restart MCPE. Can you help me?

**Comment by GamakCZ** [comment]
What version of mcpe are you using?

**Comment by HimmelKreis4865** [comment]
1.12.1, the latest one...
And **every** player on the server has this problem

**Comment by GamakCZ** [comment]
Seems strange

**Comment by ZZWILLIAMXXTrue** [comment]
I also have that problem, sometimes is works, sometimes it doesnt

**Comment by Wertzui123** [comment]
Loading screen? Do you use a plugin to add the nether?

**Comment by GamakCZ** [comment]
Probably fixed by mojang.
