### ISSUE TITLE
Random spawn when dead

### ISSUE THREAD

**Issue by DaRealPizza** [CzechPMDevs/MultiWorld#70]
I have an issue with spawn points. All spawns work fine, default worlds and typing all work. But when someone dies, it tps them to a random location in the world they died in. I would want it to tp you to the spawn of the world, or better, a different world. How do fix/do this? 

Plugin has the latest version (I don't know it) 

The version of pocketmine is 3.9.4

I would love it if someone helps, thanks!

**Comment by GamakCZ** [comment]
This problem shouldn't been caused by MultiWorld... Check other plugins that you are using.
