### ISSUE TITLE
gamerule does not work

### ISSUE THREAD

**Issue by mnkarm** [CzechPMDevs/MultiWorld#79]
hi! when i type /gamerule or /mw gamerule <gamerule> <false|true> [world]
it says world true|false not found 
can you fix it

btw good plugin

**Comment by CoolStuff08** [comment]
try /mw gamerule <world> <true|false> instead

**Comment by GamakCZ** [comment]
For me it works fine. Could you please send video with reproducing the issue or something equal to this?

**Comment by mnkarm** [comment]
when i remove the level it works but i want the gamerule in a wotld not all of it

**Comment by GamakCZ** [comment]
Wdym? It works that each level has own gamerules..

**Comment by mnkarm** [comment]
oh ok now i understand thanks!!
