### ISSUE TITLE
Chunk don't load

### ISSUE THREAD

**Issue by RinoXz** [CzechPMDevs/MultiWorld#83]
I have a map who use the custom generator but the chunk where the players disconnect don't load. After, if the player want to join the server, he research this It goes on indefinitely so i must restart the server .
To make it normal again .

but the bug sometimes reappears after 5-6 hours or several days.

I use pmmp 3.11.5 and the version 1.5.2 (last poggit release) of MultiWorld).

**Comment by GamakCZ** [comment]
Which generator have you used? Also, was something written in console?

**Comment by RinoXz** [comment]
I use the custom generator (implanted on 1.5.2) an there is no mistake in the console.

**Comment by GamakCZ** [comment]
Are you sure?

**Comment by RinoXz** [comment]
I have this mistake ( i have check the logs) :

[Asynchronous Worker #3 thread/CRITICAL]: TypeError: "Return value of pocketmine\level\biome\Biome::getMinElevation() must be of the type int, null returned" (EXCEPTION) in "src/pocketmine/level/biome/Biome" at line 160

[Asynchronous Worker #3 thread/DEBUG]: #0 plugins/MultiWorld.phar/src/czechpmdevs/multiworld/generator/normal/NormalGenerator(188): pocketmine\level\biome\Biome->getMinElevation()

[Asynchronous Worker #3 thread/DEBUG]: #1 src/pocketmine/level/generator/PopulationTask(108): czechpmdevs\multiworld\generator\normal\NormalGenerator->generateChunk(integer 192, integer -56)

[Asynchronous Worker #3 thread/DEBUG]: #2 src/pocketmine/scheduler/AsyncTask(82): pocketmine\level\generator\PopulationTask->onRun()

[Asynchronous Worker #3 thread/DEBUG]: #3 (): pocketmine\scheduler\AsyncTask->run()


[Server thread/CRITICAL]: Could not execute asynchronous task PopulationTask: Task crashed

**Comment by RinoXz** [comment]
It's like the #82 .

Can I patch this without reset the world ?

**Comment by GamakCZ** [comment]
Can you please attach multiworld phar you are using?

**Comment by RinoXz** [comment]
I use the version 1.5.2 of MultiWorld (latest
[MultiWorld.zip](https://github.com/CzechPMDevs/MultiWorld/files/4267903/MultiWorld.zip)
 release on poggit).

**Comment by GamakCZ** [comment]
strange

**Comment by RinoXz** [comment]
So, how I can patch this bug ?

**Comment by RinoXz** [comment]
This problem can be resolve with a plugin who populate chunk ?

**Comment by GamakCZ** [comment]
You aren't using custom generator, but normal

**Comment by RinoXz** [comment]
I use the custom generator implements on the 1.5.2 (with generatorName : normal_mw).
Therefore i Don't know how i can patch this error

**Comment by RinoXz** [comment]
I have use this command: /mw create MyWorld (0 or random number) custom

**Comment by RinoXz** [comment]
This error occurs when i am teleport on a not populated chunk (Some chunks around load but other chunk have the error and don't load).

**Comment by RinoXz** [comment]
I use also the first version of 1.5.2 publish on poggit. Not one of the other build who's published after.

**Comment by RinoXz** [comment]
Can you answer me? Because of this problem, many players can not connect

**Comment by GamakCZ** [comment]
You can use the older version which has not improved generator, but it should work.

**Comment by RinoXz** [comment]
If i use the version 1.5.1, my world with generator normal_mw can work ?

**Comment by GamakCZ** [comment]
yep, it will use default instead if the custom doesn't exist.

**Comment by RinoXz** [comment]
Okay, and the custom biomes are not gerenate if i use the 1.5.1 ?

**Comment by GamakCZ** [comment]
probably no

**Comment by RinoXz** [comment]
He can do a corruption of the map/chunks ?

**Comment by RinoXz** [comment]
I must use

**Comment by RinoXz** [comment]
?

**Comment by GamakCZ** [comment]
Do you have discord?

**Comment by RinoXz** [comment]
Yes, Tota77#1921

**Comment by NormalOcean6686** [comment]
Same issue with custom worlds loading slow

**Comment by MonoAdrian23** [comment]
Fly in a Custom Generator World is not possible too.
Chunks crashed when you fly in a Custom Generator

**Comment by JoshuaPHYT** [comment]
Still not fixed hmmmmm

**Comment by MonoAdrian23** [comment]
Change youre Software to PowerNukkit.
Pocketmine is down.

**Comment by MonoAdrian23** [comment]
Multiworld is outdated
