### ISSUE TITLE
Mesa and Jungle biomes

### ISSUE THREAD

**Issue by Killian92** [CzechPMDevs/MultiWorld#88]
Big praise for the new biomes !!!!!!!!!
Please add Mesa and Jungle.
Multiworld is now the best there is.

**Comment by llPushkarSinghll** [comment]
Add caves also ._.

**Comment by VixikHD** [comment]
> Add caves also ._.

Caves are already added in custom generator. Also for new feature please create a new issue. 🤦🏼
