### ISSUE TITLE
Teleport between worlds

### ISSUE THREAD

**Issue by MariusMRN** [CzechPMDevs/MultiWorld#90]
- Issue Description: When i'm trying to teleport to another world, i get this error: https://prnt.sc/rknqe3

- Version: Last from github ( v1.6.0-beta1 )

- Server Version:  PocketMine-MP 3.11.6

- Crashdump, backtrace or other files:

**Comment by GamakCZ** [comment]
The world is downloaded or generated on the server?

**Comment by GamakCZ** [comment]
Temporary closed until further information
