### ISSUE TITLE
Bug Chunks not load

### ISSUE THREAD

**Issue by Centoller** [CzechPMDevs/MultiWorld#92]
- using the custom generator makes some chunks not load, it is solved by giving / mw unload to the world every 1 hour, but I hope soon they can fix it, since it also makes players who disconnect in that world cannot access until they are do / mw unload

- Version: 1.5.2

- Server Version: Pocketmine 3.11.6

- Crashdump, backtrace or other files:

**Comment by GamakCZ** [comment]
What do you mean by 'not load'? They aren't displayed?

**Comment by mikeygio10** [comment]
They also generate slow. If you have /wild then it takes 5s to 10s for the chunk you are in to load

**Comment by Centoller** [comment]
I just don't see anything, a void, my server has 12 ram so I don't think it's the power, and I have programmed the / mw unload command to run every hour, so that error doesn't happen,

**Comment by GamakCZ** [comment]
Php isn't language made for generating worlds. It's language made for making intelligent webpages. That's the reason why it's so slow. If you rewrite that code to java, the world will be generated faster...

**Comment by GamakCZ** [comment]
Do you have discord @Centoller ?

**Comment by Centoller** [comment]
Yes, Centoller#1638

**Comment by MonoAdrian23** [comment]
Set Async to Auto in pocketmine.yml
Problem solved!

**Comment by MCPEATECH** [comment]
I have this same issue. When running this plugin on pocketmine after 5/10 minutes the world stops loading. No errors. @MonoAdrian23 That doesn't seem to fix anything.

**Comment by MonoAdrian23** [comment]
Use the Release Version of Multiworld.

**Comment by MCPEATECH** [comment]
I am using 1.5.2 (phar) from poggit.

**Comment by Meltinglce** [comment]
can you remove me as a contributor because i don't want these notification anymore

**Comment by MonoAdrian23** [comment]
Use a Version without Custom Generator.

**Comment by DerCooleVonDem** [comment]
> They also generate slow. If you have /wild then it takes 5s to 10s for the chunk you are in to load

This depends on the server hardware and on your or your player internet

**Comment by VixikHD** [comment]
Create a new issue if the problem occurs again.
