### ISSUE TITLE
Gamerule and command add

### ISSUE THREAD

**Issue by HugoLeBoss91** [CzechPMDevs/MultiWorld#98]
Add new gamerule: breack:
 place:
interact: 
eternal day:
 rain: 
thunderstorm: 
open chest: 
spawn entities: (compatible with PureEntities)
 max player: 

Add the command: / mw info
 Example: 

---- Lobby ---- 
player: 1/100 
tps: 20.0 
load: 50% 
structure: 200 
  - Village: 100  
  - Igloo: 100  
  - ... 

Add the possibility to locate and create structures manually: 

/mw structure locate {name of structure} 

Example: 
Village: 1234, 68, 6939

 / mw structure spawn {name of structure}

**Comment by GamakCZ** [comment]
- Other game rules must be first implemented by server software (the specified you want didn't implement neither mojang yet.)
- Info command is already added
- Structures aren't added to generator
